import re
language_patterns = {
    "actionscript": {"license": "MIT License","filename": re.compile(r"^.*\.(as)$", re.IGNORECASE),"content":None,},
    "ada": {"license": "MIT License","filename": re.compile(r"^.*\.(ada|adb|ads)$", re.IGNORECASE),"content":None,},
    "agda": {"license": "MIT License","filename": re.compile(r"^.*\.(agda)$", re.IGNORECASE),"content":None,},
    "apex": {"license": "MIT License","filename": re.compile(r"^.*\.(apex)$", re.IGNORECASE),"content":None,},
    "arduino": {"license": "MIT License","filename": re.compile(r"^.*\.(ino)$", re.IGNORECASE),"content":None,},
    "asm": {"license": "MIT License","filename": re.compile(r"^.*\.(S|s)$", re.IGNORECASE),"content":None,},
    "astro": {"license": "MIT License","filename": re.compile(r"^$", re.IGNORECASE),"content":None,},
    "bash": {"license": "MIT License","filename": re.compile(r"^.*\.(bash|ebuild|eclass|exheres\-0|exlib|ksh|sh|zsh)$", re.IGNORECASE),"content":None,},
    "beancount": {"license": "MIT License","filename": re.compile(r"^$", re.IGNORECASE),"content":None,},
    "bibtex": {"license": "MIT License","filename": re.compile(r"^.*\.(bib)$", re.IGNORECASE),"content":None,},
    "bicep": {"license": "MIT License","filename": re.compile(r"^$", re.IGNORECASE),"content":None,},
    "bitbake": {"license": "MIT License","filename": re.compile(r"^$", re.IGNORECASE),"content":None,},
    "c": {"license": "MIT License","filename": re.compile(r"^.*\.(c|h|idc|x\[bp\]m)$", re.IGNORECASE),"content":None,},
    "cairo": {"license": "MIT License","filename": re.compile(r"^$", re.IGNORECASE),"content":None,},
    "capnp": {"license": "MIT License","filename": re.compile(r"^.*\.(capnp)$", re.IGNORECASE),"content":None,},
    "chatito": {"license": "MIT License","filename": re.compile(r"^$", re.IGNORECASE),"content":None,},
    "clarity": {"license": "MIT License","filename": re.compile(r"^$", re.IGNORECASE),"content":None,},
    "clojure": {"license": "CC0 1.0 Universal License","filename": re.compile(r"^.*\.(clj|cljc)$", re.IGNORECASE),"content":None,},
    "cmake": {"license": "MIT License","filename": re.compile(r"^.*\.(cmake)$", re.IGNORECASE),"content":None,},
    "comment": {"license": "MIT License","filename": re.compile(r"^$", re.IGNORECASE),"content":None,},
    "commonlisp": {"license": "MIT License","filename": re.compile(r"^.*\.(lsp)$", re.IGNORECASE),"content":None,},
    "cpon": {"license": "MIT License","filename": re.compile(r"^$", re.IGNORECASE),"content":None,},
    "cpp": {"license": "MIT License","filename": re.compile(r"^.*\.(C|CPP|H|c\+\+|cc|cp|cpp|cxx|h\+\+|hh|hpp|hxx|tpp)$", re.IGNORECASE),"content":None,},
    "csharp": {"license": "MIT License","filename": re.compile(r"^.*\.(cs)$", re.IGNORECASE),"content":None,},
    "css": {"license": "MIT License","filename": re.compile(r"^.*\.(css,tcss)$", re.IGNORECASE),"content":None,},
    "csv": {"license": "MIT License","filename": re.compile(r"^.*\.(csv)$", re.IGNORECASE),"content":None,},
    "cuda": {"license": "MIT License","filename": re.compile(r"^.*\.(cu|cuh)$", re.IGNORECASE),"content":None,},
    "d": {"license": "MIT License","filename": re.compile(r"^.*\.(d|di)$", re.IGNORECASE),"content":None,},
    "dart": {"license": "MIT License","filename": re.compile(r"^.*\.(dart)$", re.IGNORECASE),"content":None,},
    "dockerfile": {"license": "MIT License","filename": re.compile(r"^.*\.(docker)$", re.IGNORECASE),"content":None,},
    "doxygen": {"license": "MIT License","filename": re.compile(r"^.*\.(doxygen)$", re.IGNORECASE),"content":None,},
    "dtd": {"license": "MIT License","filename": re.compile(r"^.*\.(dtd)$", re.IGNORECASE),"content":None,},
    "elisp": {"license": "MIT License","filename": re.compile(r"^.*\.(el)$", re.IGNORECASE),"content":None,},
    "elixir": {"license": "MIT License","filename": re.compile(r"^.*\.(eex|ex|exs|leex)$", re.IGNORECASE),"content":None,},
    "elm": {"license": "MIT License","filename": re.compile(r"^.*\.(elm)$", re.IGNORECASE),"content":None,},
    "embeddedtemplate": {"license": "MIT License","filename": re.compile(r"^$", re.IGNORECASE),"content":None,},
    "erlang": {"license": "MIT License","filename": re.compile(r"^.*\.(erl|es|escript|hrl)$", re.IGNORECASE),"content":None,},
    "fennel": {"license": "MIT License","filename": re.compile(r"^.*\.(fnl)$", re.IGNORECASE),"content":None,},
    "firrtl": {"license": "Apache License 2.0","filename": re.compile(r"^$", re.IGNORECASE),"content":None,},
    "fish": {"license": "Unlicense license","filename": re.compile(r"^.*\.(fish|load)$", re.IGNORECASE),"content":None,},
    "fortran": {"license": "MIT License","filename": re.compile(r"^.*\.(F03|F90|f03|f90)$", re.IGNORECASE),"content":None,},
    "func": {"license": "MIT License","filename": re.compile(r"^.*\.(fc|func)$", re.IGNORECASE),"content":None,},
    "gdscript": {"license": "MIT License","filename": re.compile(r"^.*\.(gd)$", re.IGNORECASE),"content":None,},
    "gitattributes": {"license": "MIT License","filename": re.compile(r"^\.gitattributes$", re.IGNORECASE),"content":None,},
    "gitcommit": {"license": "WTFPL License","filename": re.compile(r"^$", re.IGNORECASE),"content":None,},
    "gitignore": {"license": "MIT License","filename": re.compile(r"^\.gitignore$", re.IGNORECASE),"content":None,},
    "gleam": {"license": "Apache-2.0 license","filename": re.compile(r"^.*\.(gleam)$", re.IGNORECASE),"content":None,},
    "glsl": {"license": "MIT License","filename": re.compile(r"^.*\.(frag|geo|vert)$", re.IGNORECASE),"content":None,},
    "gn": {"license": "MIT License","filename": re.compile(r"^$", re.IGNORECASE),"content":None,},
    "go": {"license": "MIT License","filename": re.compile(r"^.*\.(go)$", re.IGNORECASE),"content":None,},
    "gomod": {"license": "MIT License","filename": re.compile(r"^$", re.IGNORECASE),"content":None,},
    "gosum": {"license": "MIT License","filename": re.compile(r"^$", re.IGNORECASE),"content":None,},
    "graphql": {"license": "MIT License","filename": re.compile(r"^.*\.(graphql)$", re.IGNORECASE),"content":None,},
    "groovy": {"license": "MIT License","filename": re.compile(r"^.*\.(gradle|groovy)$", re.IGNORECASE),"content":None,},
    "gstlaunch": {"license": "MIT License","filename": re.compile(r"^$", re.IGNORECASE),"content":None,},
    "hack": {"license": "MIT License","filename": re.compile(r"^$", re.IGNORECASE),"content":None,},
    "hare": {"license": "MIT License","filename": re.compile(r"^.*\.(ha)$", re.IGNORECASE),"content":None,},
    "haskell": {"license": "MIT License","filename": re.compile(r"^.*\.(hs)$", re.IGNORECASE),"content":None,},
    "haxe": {"license": "MIT License","filename": re.compile(r"^.*\.(hx|hxsl)$", re.IGNORECASE),"content":None,},
    "hcl": {"license": "Apache License 2.0","filename": re.compile(r"^.*\.(hcl|tf)$", re.IGNORECASE),"content":None,},
    "heex": {"license": "MIT License","filename": re.compile(r"^$", re.IGNORECASE),"content":None,},
    "hlsl": {"license": "MIT License","filename": re.compile(r"^.*\.(hlsl|hlsli)$", re.IGNORECASE),"content":None,},
    "html": {"license": "MIT License","filename": re.compile(r"^.*\.(htm|html|xhtml|xslt)$", re.IGNORECASE),"content":None,},
    "hyprlang": {"license": "MIT License","filename": re.compile(r"^$", re.IGNORECASE),"content":None,},
    "ispc": {"license": "MIT License","filename": re.compile(r"^$", re.IGNORECASE),"content":None,},
    "janet": {"license": "BSD-3-Clause license","filename": re.compile(r"^.*\.(janet|jdn)$", re.IGNORECASE),"content":None,},
    "java": {"license": "MIT License","filename": re.compile(r"^.*\.(java)$", re.IGNORECASE),"content":None,},
    "javascript": {"license": "MIT License","filename": re.compile(r"^.*\.(cjs|js|jsm|mjs)$", re.IGNORECASE),"content":None,},
    "jsdoc": {"license": "MIT License","filename": re.compile(r"^.*\.(jsdoc)$", re.IGNORECASE),"content":None,},
    "json": {"license": "MIT License","filename": re.compile(r"^.*\.(json|jsonl|ndjson)$", re.IGNORECASE),"content":None,},
    "jsonnet": {"license": "MIT License","filename": re.compile(r"^.*\.(jsonnet|libsonnet)$", re.IGNORECASE),"content":None,},
    "julia": {"license": "MIT License","filename": re.compile(r"^.*\.(jl)$", re.IGNORECASE),"content":None,},
    "kconfig": {"license": "MIT License","filename": re.compile(r"^$", re.IGNORECASE),"content":None,},
    "kdl": {"license": "MIT License","filename": re.compile(r"^$", re.IGNORECASE),"content":None,},
    "kotlin": {"license": "MIT License","filename": re.compile(r"^.*\.(kt|kts)$", re.IGNORECASE),"content":None,},
    "latex": {"license": "MIT License","filename": re.compile(r"^.*\.(aux|tex|toc)$", re.IGNORECASE),"content":None,},
    "linkerscript": {"license": "MIT License","filename": re.compile(r"^$", re.IGNORECASE),"content":None,},
    "llvm": {"license": "MIT License","filename": re.compile(r"^.*\.(ll)$", re.IGNORECASE),"content":None,},
    "lua": {"license": "MIT License","filename": re.compile(r"^.*\.(lua|wlua)$", re.IGNORECASE),"content":None,},
    "luadoc": {"license": "MIT License","filename": re.compile(r"^$", re.IGNORECASE),"content":None,},
    "luap": {"license": "MIT License","filename": re.compile(r"^$", re.IGNORECASE),"content":None,},
    "luau": {"license": "MIT License","filename": re.compile(r"^.*\.(luau)$", re.IGNORECASE),"content":None,},
    "magik": {"license": "MIT License","filename": re.compile(r"^$", re.IGNORECASE),"content":None,},
    "make": {"license": "MIT License","filename": re.compile(r"^.*\.(mak|mk)$", re.IGNORECASE),"content":None,},
    "markdown": {"license": "MIT License","filename": re.compile(r"^.*\.(markdown|md)$", re.IGNORECASE),"content":None,},
    "markdown_inline": {"license": "MIT License","filename": re.compile(r"^$", re.IGNORECASE),"content":None,},
    "matlab": {"license": "MIT License","filename": re.compile(r"^.*\.(m)$", re.IGNORECASE),"content":None,},
    "mermaid": {"license": "MIT License","filename": re.compile(r"^.*\.(mermaid)$", re.IGNORECASE),"content":None,},
    "meson": {"license": "MIT License","filename": re.compile(r"^.*\.(meson)$", re.IGNORECASE),"content":None,},
    "netlinx": {"license": "MIT License","filename": re.compile(r"^netlinx$", re.IGNORECASE),"content":None,},
    "ninja": {"license": "MIT License","filename": re.compile(r"^ninja$", re.IGNORECASE),"content":None,},
    "nix": {"license": "MIT License","filename": re.compile(r"^.*\.(nix)$", re.IGNORECASE),"content":None,},
    "nqc": {"license": "MIT License","filename": re.compile(r"^$", re.IGNORECASE),"content":None,},
    "objc": {"license": "MIT License","filename": re.compile(r"^.*\.(h|m)$", re.IGNORECASE),"content":None,},
    "ocaml/ocaml_interface": {"license": "MIT License","filename": re.compile(r"^.*\.(ml|mli|mll|mly)$", re.IGNORECASE),"content":None,},
    "odin": {"license": "MIT License","filename": re.compile(r"^.*\.(odin)$", re.IGNORECASE),"content":None,},
    "org": {"license": "MIT License","filename": re.compile(r"^.*\.(org)$", re.IGNORECASE),"content":None,},
    "pascal": {"license": "MIT License","filename": re.compile(r"^.*\.(dpr|pas)$", re.IGNORECASE),"content":None,},
    "pem": {"license": "MIT License","filename": re.compile(r"^.*\.(asc|pem)$", re.IGNORECASE),"content":None,},
    "perl": {"license": "Artistic License 2.0","filename": re.compile(r"^.*\.(perl|pl|pm|t)$", re.IGNORECASE),"content":None,},
    "pgn": {"license": "BSD-2-Clause license","filename": re.compile(r"^$", re.IGNORECASE),"content":None,},
    "php": {"license": "MIT License","filename": re.compile(r"^.*\.(inc|php|php\[345\])$", re.IGNORECASE),"content":None,},
    "po": {"license": "MIT License","filename": re.compile(r"^.*\.(po|pot)$", re.IGNORECASE),"content":None,},
    "pony": {"license": "MIT License","filename": re.compile(r"^.*\.(pony)$", re.IGNORECASE),"content":None,},
    "powershell": {"license": "MIT License","filename": re.compile(r"^.*\.(ps1|psm1)$", re.IGNORECASE),"content":None,},
    "printf": {"license": "ISC License","filename": re.compile(r"^$", re.IGNORECASE),"content":None,},
    "prisma": {"license": "MIT License","filename": re.compile(r"^$", re.IGNORECASE),"content":None,},
    "properties": {"license": "MIT License","filename": re.compile(r"^.*\.(properties)$", re.IGNORECASE),"content":None,},
    "proto": {"license": "MIT License","filename": re.compile(r"^.*\.(proto)$", re.IGNORECASE),"content":None,},
    "psv": {"license": "MIT License","filename": re.compile(r"^.*\.(psv)$", re.IGNORECASE),"content":None,},
    "puppet": {"license": "MIT License","filename": re.compile(r"^.*\.(pp)$", re.IGNORECASE),"content":None,},
    "purescript": {"license": "MIT License","filename": re.compile(r"^$", re.IGNORECASE),"content":None,},
    "pymanifest": {"license": "MIT License","filename": re.compile(r"^pymanifest$", re.IGNORECASE),"content":None,},
    "python": {"license": "MIT License","filename": re.compile(r"^.*\.(bzl|jy|py|pyi|pyw|sage|sc|tac)$", re.IGNORECASE),"content":None,},
    "qmldir": {"license": "MIT License","filename": re.compile(r"^.*\.(qmldir)$", re.IGNORECASE),"content":None,},
    "qmljs": {"license": "MIT License","filename": re.compile(r"^.*\.(qmljs)$", re.IGNORECASE),"content":None,},
    "query": {"license": "Apache License 2.0","filename": re.compile(r"^$", re.IGNORECASE),"content":None,},
    "r": {"license": "MIT License","filename": re.compile(r"^.*\.(R|S)$", re.IGNORECASE),"content":None,},
    "racket": {"license": "MIT License","filename": re.compile(r"^.*\.(rkt|rktd|rktl)$", re.IGNORECASE),"content":None,},
    "rbs": {"license": "MIT License","filename": re.compile(r"^.*\.(rbs)$", re.IGNORECASE),"content":None,},
    "re2c": {"license": "MIT License","filename": re.compile(r"^$", re.IGNORECASE),"content":None,},
    "readline": {"license": "MIT License","filename": re.compile(r"^$", re.IGNORECASE),"content":None,},
    "rego": {"license": "MIT License","filename": re.compile(r"^.*\.(rego)$", re.IGNORECASE),"content":None,},
    "requirements": {"license": "MIT License","filename": re.compile(r"^requirements.txt$", re.IGNORECASE),"content":None,},
    "ron": {"license": "Apache License 2.0","filename": re.compile(r"^$", re.IGNORECASE),"content":None,},
    "rst": {"license": "MIT License","filename": re.compile(r"^.*\.(rest|rst)$", re.IGNORECASE),"content":None,},
    "ruby": {"license": "MIT License","filename": re.compile(r"^.*\.(duby|gemspec|rake|rb|rbw|rbx)$", re.IGNORECASE),"content":None,},
    "rust": {"license": "MIT License","filename": re.compile(r"^.*\.(in|rs)$", re.IGNORECASE),"content":None,},
    "scala": {"license": "MIT License","filename": re.compile(r"^.*\.(scala)$", re.IGNORECASE),"content":None,},
    "scheme": {"license": "MIT License","filename": re.compile(r"^.*\.(scm|ss)$", re.IGNORECASE),"content":None,},
    "scss": {"license": "MIT License","filename": re.compile(r"^.*\.(scss)$", re.IGNORECASE),"content":None,},
    "slang": {"license": "MIT License","filename": re.compile(r"^$", re.IGNORECASE),"content":None,},
    "smali": {"license": "MIT License","filename": re.compile(r"^.*\.(smali)$", re.IGNORECASE),"content":None,},
    "smithy": {"license": "MIT License","filename": re.compile(r"^.*\.(smithy)$", re.IGNORECASE),"content":None,},
    "solidity": {"license": "MIT License","filename": re.compile(r"^.*\.(sol)$", re.IGNORECASE),"content":None,},
    "sparql": {"license": "MIT License","filename": re.compile(r"^.*\.(rq|sparql)$", re.IGNORECASE),"content":None,},
    "sql": {"license": "MIT License","filename": re.compile(r"^.*\.(sql)$", re.IGNORECASE),"content":None,},
    "squirrel": {"license": "MIT License","filename": re.compile(r"^$", re.IGNORECASE),"content":None,},
    "starlark": {"license": "MIT License","filename": re.compile(r"^.*\.(bzl|jy|py|pyi|pyw|sage|sc|tac)$", re.IGNORECASE),"content":None,},
    "svelte": {"license": "MIT License","filename": re.compile(r"^.*\.(svelte)$", re.IGNORECASE),"content":None,},
    "swift": {"license": "MIT License","filename": re.compile(r"^.*\.(swift)$", re.IGNORECASE),"content":None,},
    "tablegen": {"license": "MIT License","filename": re.compile(r"^.*\.(td)$", re.IGNORECASE),"content":None,},
    "tcl": {"license": "MIT License","filename": re.compile(r"^.*\.(rvt|tcl)$", re.IGNORECASE),"content":None,},
    "test": {"license": "MIT License","filename": re.compile(r"^$", re.IGNORECASE),"content":None,},
    "thrift": {"license": "MIT License","filename": re.compile(r"^.*\.(thrift)$", re.IGNORECASE),"content":None,},
    "toml": {"license": "MIT License","filename": re.compile(r"^.*\.(toml)$", re.IGNORECASE),"content":None,},
    "tsv": {"license": "MIT License","filename": re.compile(r"^.*\.(tsv)$", re.IGNORECASE),"content":None,},
    "tsx": {"license": "MIT License","filename": re.compile(r"^.*\.(tsx)$", re.IGNORECASE),"content":None,},
    "twig": {"license": "WTFPL License","filename": re.compile(r"^.*\.(twig)$", re.IGNORECASE),"content":None,},
    "typescript": {"license": "MIT License","filename": re.compile(r"^.*\.(ts)$", re.IGNORECASE),"content":None,},
    "typst": {"license": "MIT License","filename": re.compile(r"^.*\.(typ)$", re.IGNORECASE),"content":None,},
    "udev": {"license": "MIT License","filename": re.compile(r"^$", re.IGNORECASE),"content":None,},
    "ungrammar": {"license": "MIT License","filename": re.compile(r"^$", re.IGNORECASE),"content":None,},
    "uxntal": {"license": "MIT License","filename": re.compile(r"^.*\.(tal)$", re.IGNORECASE),"content":None,},
    "v": {"license": "MIT License","filename": re.compile(r"^.*\.(v)$", re.IGNORECASE),"content":None,},
    "verilog": {"license": "MIT License","filename": re.compile(r"^.*\.(v)$", re.IGNORECASE),"content":None,},
    "vhdl": {"license": "MIT License","filename": re.compile(r"^.*\.(vhd|vhdl)$", re.IGNORECASE),"content":None,},
    "vim": {"license": "MIT License","filename": re.compile(r"^.*\.(vim)$", re.IGNORECASE),"content":None,},
    "vue": {"license": "MIT License","filename": re.compile(r"^.*\.(vue)$", re.IGNORECASE),"content":None,},
    "wgsl": {"license": "MIT License","filename": re.compile(r"^.*\.(wgsl)$", re.IGNORECASE),"content":None,},
    "xcompose": {"license": "MIT License","filename": re.compile(r"^$", re.IGNORECASE),"content":None,},
    "xml": {"license": "MIT License","filename": re.compile(r"^.*\.(rss|wsdl|wsf|xml|xsd|xsl|xslt)$", re.IGNORECASE),"content":None,},
    "yaml": {"license": "MIT License","filename": re.compile(r"^.*\.(yaml|yml)$", re.IGNORECASE),"content":None,},
    "yuck": {"license": "MIT License","filename": re.compile(r"^.*\.(yuck)$", re.IGNORECASE),"content":None,},
    "zig": {"license": "MIT License","filename": re.compile(r"^.*\.(zig)$", re.IGNORECASE),"content":None,},
}
languages = {
    "abap": {"filename": re.compile(r'^.*.(ABAP,abap)$', re.IGNORECASE),"content":None,},
    "abl": {"filename": re.compile(r'^.*.(cls,p)$', re.IGNORECASE),"content":None,},
    "abnf": {"filename": re.compile(r'^.*.(abnf)$', re.IGNORECASE),"content":None,},
    "actionscript": {"filename": re.compile(r'^.*.(as)$', re.IGNORECASE),"content":None,},
    "actionscript3": {"filename": re.compile(r'^.*.(as)$', re.IGNORECASE),"content":None,},
    "ada": {"filename": re.compile(r'^.*.(ada,adb,ads)$', re.IGNORECASE),"content":None,},
    "ada2005": {"filename": re.compile(r'^.*.(ada,adb,ads)$', re.IGNORECASE),"content":None,},
    "ada95": {"filename": re.compile(r'^.*.(ada,adb,ads)$', re.IGNORECASE),"content":None,},
    "adl": {"filename": re.compile(r'^.*.(adl,adlf,adls,adlx)$', re.IGNORECASE),"content":None,},
    "agda": {"filename": re.compile(r'^.*.(agda)$', re.IGNORECASE),"content":None,},
    "aheui": {"filename": re.compile(r'^.*.(aheui)$', re.IGNORECASE),"content":None,},
    "ahk": {"filename": re.compile(r'^.*.(ahk,ahkl)$', re.IGNORECASE),"content":None,},
    "alloy": {"filename": re.compile(r'^.*.(als)$', re.IGNORECASE),"content":None,},
    "ambienttalk": {"filename": re.compile(r'^.*.(at)$', re.IGNORECASE),"content":None,},
    "ambienttalk/2": {"filename": re.compile(r'^.*.(at)$', re.IGNORECASE),"content":None,},
    "amdgpu": {"filename": re.compile(r'^.*.(isa)$', re.IGNORECASE),"content":None,},
    "ampl": {"filename": re.compile(r'^.*.(run)$', re.IGNORECASE),"content":None,},
    "ansys": {"filename": re.compile(r'^.*.(ans)$', re.IGNORECASE),"content":None,},
    "antlr-actionscript": {"filename": re.compile(r'^.*.(G,g)$', re.IGNORECASE),"content":None,},
    "antlr-as": {"filename": re.compile(r'^.*.(G,g)$', re.IGNORECASE),"content":None,},
    "antlr-c#": {"filename": re.compile(r'^.*.(G,g)$', re.IGNORECASE),"content":None,},
    "antlr-cpp": {"filename": re.compile(r'^.*.(G,g)$', re.IGNORECASE),"content":None,},
    "antlr-csharp": {"filename": re.compile(r'^.*.(G,g)$', re.IGNORECASE),"content":None,},
    "antlr-java": {"filename": re.compile(r'^.*.(G,g)$', re.IGNORECASE),"content":None,},
    "antlr-objc": {"filename": re.compile(r'^.*.(G,g)$', re.IGNORECASE),"content":None,},
    "antlr-perl": {"filename": re.compile(r'^.*.(G,g)$', re.IGNORECASE),"content":None,},
    "antlr-python": {"filename": re.compile(r'^.*.(G,g)$', re.IGNORECASE),"content":None,},
    "antlr-rb": {"filename": re.compile(r'^.*.(G,g)$', re.IGNORECASE),"content":None,},
    "antlr-ruby": {"filename": re.compile(r'^.*.(G,g)$', re.IGNORECASE),"content":None,},
    "apdl": {"filename": re.compile(r'^.*.(ans)$', re.IGNORECASE),"content":None,},
    "apl": {"filename": re.compile(r'^.*.(apl,aplc,aplf,apli,apln,aplo,dyalog)$', re.IGNORECASE),"content":None,},
    "applescript": {"filename": re.compile(r'^.*.(applescript)$', re.IGNORECASE),"content":None,},
    "arduino": {"filename": re.compile(r'^.*.(ino)$', re.IGNORECASE),"content":None,},
    "arexx": {"filename": re.compile(r'^.*.(arexx,rex,rexx,rx)$', re.IGNORECASE),"content":None,},
    "arrow": {"filename": re.compile(r'^.*.(arw)$', re.IGNORECASE),"content":None,},
    "art": {"filename": re.compile(r'^.*.(art)$', re.IGNORECASE),"content":None,},
    "arturo": {"filename": re.compile(r'^.*.(art)$', re.IGNORECASE),"content":None,},
    "as": {"filename": re.compile(r'^.*.(as)$', re.IGNORECASE),"content":None,},
    "as3": {"filename": re.compile(r'^.*.(as)$', re.IGNORECASE),"content":None,},
    "asc": {"filename": re.compile(r'^.*.(asc,pem)$', re.IGNORECASE),"content":None,},
    "asm": {"filename": re.compile(r'^.*.(S,s)$', re.IGNORECASE),"content":None,},
    "asn1": {"filename": re.compile(r'^.*.(asn1)$', re.IGNORECASE),"content":None,},
    "aspectj": {"filename": re.compile(r'^.*.(aj)$', re.IGNORECASE),"content":None,},
    "aspx-cs": {"filename": re.compile(r'^.*.(asax,ascx,ashx,asmx,aspx,axd)$', re.IGNORECASE),"content":None,},
    "aspx-vb": {"filename": re.compile(r'^.*.(asax,ascx,ashx,asmx,aspx,axd)$', re.IGNORECASE),"content":None,},
    "asy": {"filename": re.compile(r'^.*.(asy)$', re.IGNORECASE),"content":None,},
    "asymptote": {"filename": re.compile(r'^.*.(asy)$', re.IGNORECASE),"content":None,},
    "at": {"filename": re.compile(r'^.*.(at)$', re.IGNORECASE),"content":None,},
    "augeas": {"filename": re.compile(r'^.*.(aug)$', re.IGNORECASE),"content":None,},
    "autohotkey": {"filename": re.compile(r'^.*.(ahk,ahkl)$', re.IGNORECASE),"content":None,},
    "autoit": {"filename": re.compile(r'^.*.(au3)$', re.IGNORECASE),"content":None,},
    "awk": {"filename": re.compile(r'^.*.(awk)$', re.IGNORECASE),"content":None,},
    "b3d": {"filename": re.compile(r'^.*.(bb,decls)$', re.IGNORECASE),"content":None,},
    "bare": {"filename": re.compile(r'^.*.(bare)$', re.IGNORECASE),"content":None,},
    "bash": {"filename": re.compile(r'^.*.(bash,ebuild,eclass,exheres-0,exlib,ksh,sh,zsh)$', re.IGNORECASE),"content":None,},
    "basic": {"filename": re.compile(r'^.*.(BAS,bas)$', re.IGNORECASE),"content":None,},
    "bat": {"filename": re.compile(r'^.*.(bat,cmd)$', re.IGNORECASE),"content":None,},
    "batch": {"filename": re.compile(r'^.*.(bat,cmd)$', re.IGNORECASE),"content":None,},
    "bazel": {"filename": re.compile(r'^.*.(bzl,jy,py,pyi,pyw,sage,sc,tac)$', re.IGNORECASE),"content":None,},
    "bbcbasic": {"filename": re.compile(r'^.*.(bbc)$', re.IGNORECASE),"content":None,},
    "bc": {"filename": re.compile(r'^.*.(bc)$', re.IGNORECASE),"content":None,},
    "bdd": {"filename": re.compile(r'^.*.(feature)$', re.IGNORECASE),"content":None,},
    "be": {"filename": re.compile(r'^.*.(be)$', re.IGNORECASE),"content":None,},
    "befunge": {"filename": re.compile(r'^.*.(befunge)$', re.IGNORECASE),"content":None,},
    "berry": {"filename": re.compile(r'^.*.(be)$', re.IGNORECASE),"content":None,},
    "bf": {"filename": re.compile(r'^.*.(b,bf)$', re.IGNORECASE),"content":None,},
    "bib": {"filename": re.compile(r'^.*.(bib)$', re.IGNORECASE),"content":None,},
    "bibtex": {"filename": re.compile(r'^.*.(bib)$', re.IGNORECASE),"content":None,},
    "blitzbasic": {"filename": re.compile(r'^.*.(bb,decls)$', re.IGNORECASE),"content":None,},
    "blitzmax": {"filename": re.compile(r'^.*.(bmx)$', re.IGNORECASE),"content":None,},
    "blueprint": {"filename": re.compile(r'^.*.(blp)$', re.IGNORECASE),"content":None,},
    "bmax": {"filename": re.compile(r'^.*.(bmx)$', re.IGNORECASE),"content":None,},
    "bnf": {"filename": re.compile(r'^.*.(bnf)$', re.IGNORECASE),"content":None,},
    "boa": {"filename": re.compile(r'^.*.(boa)$', re.IGNORECASE),"content":None,},
    "boo": {"filename": re.compile(r'^.*.(boo)$', re.IGNORECASE),"content":None,},
    "boogie": {"filename": re.compile(r'^.*.(bpl)$', re.IGNORECASE),"content":None,},
    "bplus": {"filename": re.compile(r'^.*.(bb,decls)$', re.IGNORECASE),"content":None,},
    "bqn": {"filename": re.compile(r'^.*.(bqn)$', re.IGNORECASE),"content":None,},
    "brainfuck": {"filename": re.compile(r'^.*.(b,bf)$', re.IGNORECASE),"content":None,},
    "bro": {"filename": re.compile(r'^.*.(bro,zeek)$', re.IGNORECASE),"content":None,},
    "bsdmake": {"filename": re.compile(r'^.*.(mak,mk)$', re.IGNORECASE),"content":None,},
    "bst": {"filename": re.compile(r'^.*.(bst)$', re.IGNORECASE),"content":None,},
    "bst-pybtex": {"filename": re.compile(r'^.*.(bst)$', re.IGNORECASE),"content":None,},
    "bugs": {"filename": re.compile(r'^.*.(bug)$', re.IGNORECASE),"content":None,},
    "c": {"filename": re.compile(r'^.*.(c,h,idc,x[bp]m)$', re.IGNORECASE),"content":None,},
    "c#": {"filename": re.compile(r'^.*.(cs)$', re.IGNORECASE),"content":None,},
    "c++": {"filename": re.compile(r'^.*.(C,CPP,H,c\+\+,cc,cp,cpp,cxx,h\+\+,hh,hpp,hxx,tpp)$', re.IGNORECASE),"content":None,},
    "c++-objdumb": {"filename": re.compile(r'^.*.(c\+\+-objdump,cpp-objdump,cxx-objdump)$', re.IGNORECASE),"content":None,},
    "c-objdump": {"filename": re.compile(r'^.*.(c-objdump)$', re.IGNORECASE),"content":None,},
    "ca65": {"filename": re.compile(r'^.*.(s)$', re.IGNORECASE),"content":None,},
    "cadl": {"filename": re.compile(r'^.*.(cadl)$', re.IGNORECASE),"content":None,},
    "camkes": {"filename": re.compile(r'^.*.(camkes,idl4)$', re.IGNORECASE),"content":None,},
    "capdl": {"filename": re.compile(r'^.*.(cdl)$', re.IGNORECASE),"content":None,},
    "capnp": {"filename": re.compile(r'^.*.(capnp)$', re.IGNORECASE),"content":None,},
    "carbon": {"filename": re.compile(r'^.*.(carbon)$', re.IGNORECASE),"content":None,},
    "cbmbas": {"filename": re.compile(r'^.*.(bas)$', re.IGNORECASE),"content":None,},
    "cddl": {"filename": re.compile(r'^.*.(cddl)$', re.IGNORECASE),"content":None,},
    "ceylon": {"filename": re.compile(r'^.*.(ceylon)$', re.IGNORECASE),"content":None,},
    "cf3": {"filename": re.compile(r'^.*.(cf)$', re.IGNORECASE),"content":None,},
    "cfc": {"filename": re.compile(r'^.*.(cfc)$', re.IGNORECASE),"content":None,},
    "cfengine3": {"filename": re.compile(r'^.*.(cf)$', re.IGNORECASE),"content":None,},
    "cfg": {"filename": re.compile(r'^.*.(cfg,inf,ini)$', re.IGNORECASE),"content":None,},
    "cfm": {"filename": re.compile(r'^.*.(cfm,cfml)$', re.IGNORECASE),"content":None,},
    "chai": {"filename": re.compile(r'^.*.(chai)$', re.IGNORECASE),"content":None,},
    "chaiscript": {"filename": re.compile(r'^.*.(chai)$', re.IGNORECASE),"content":None,},
    "chapel": {"filename": re.compile(r'^.*.(chpl)$', re.IGNORECASE),"content":None,},
    "charmci": {"filename": re.compile(r'^.*.(ci)$', re.IGNORECASE),"content":None,},
    "cheetah": {"filename": re.compile(r'^.*.(spt,tmpl)$', re.IGNORECASE),"content":None,},
    "chpl": {"filename": re.compile(r'^.*.(chpl)$', re.IGNORECASE),"content":None,},
    "cirru": {"filename": re.compile(r'^.*.(cirru)$', re.IGNORECASE),"content":None,},
    "cl": {"filename": re.compile(r'^.*.(cl,lisp)$', re.IGNORECASE),"content":None,},
    "clay": {"filename": re.compile(r'^.*.(clay)$', re.IGNORECASE),"content":None,},
    "clean": {"filename": re.compile(r'^.*.(dcl,icl)$', re.IGNORECASE),"content":None,},
    "clipper": {"filename": re.compile(r'^.*.(PRG,prg)$', re.IGNORECASE),"content":None,},
    "clj": {"filename": re.compile(r'^.*.(clj,cljc)$', re.IGNORECASE),"content":None,},
    "cljs": {"filename": re.compile(r'^.*.(cljs)$', re.IGNORECASE),"content":None,},
    "clojure": {"filename": re.compile(r'^.*.(clj,cljc)$', re.IGNORECASE),"content":None,},
    "clojurescript": {"filename": re.compile(r'^.*.(cljs)$', re.IGNORECASE),"content":None,},
    "cmake": {"filename": re.compile(r'^.*.(cmake)$', re.IGNORECASE),"content":None,},
    "cobol": {"filename": re.compile(r'^.*.(COB,CPY,cob,cpy)$', re.IGNORECASE),"content":None,},
    "cobolfree": {"filename": re.compile(r'^.*.(CBL,cbl)$', re.IGNORECASE),"content":None,},
    "codeql": {"filename": re.compile(r'^.*.(ql,qll)$', re.IGNORECASE),"content":None,},
    "coffee": {"filename": re.compile(r'^.*.(coffee)$', re.IGNORECASE),"content":None,},
    "coffee-script": {"filename": re.compile(r'^.*.(coffee)$', re.IGNORECASE),"content":None,},
    "coffeescript": {"filename": re.compile(r'^.*.(coffee)$', re.IGNORECASE),"content":None,},
    "comal": {"filename": re.compile(r'^.*.(cml,comal)$', re.IGNORECASE),"content":None,},
    "comal80": {"filename": re.compile(r'^.*.(cml,comal)$', re.IGNORECASE),"content":None,},
    "common-lisp": {"filename": re.compile(r'^.*.(cl,lisp)$', re.IGNORECASE),"content":None,},
    "componentpascal": {"filename": re.compile(r'^.*.(cp,cps)$', re.IGNORECASE),"content":None,},
    "console": {"filename": re.compile(r'^.*.(sh-session,shell-session)$', re.IGNORECASE),"content":None,},
    "coq": {"filename": re.compile(r'^.*.(v)$', re.IGNORECASE),"content":None,},
    "cp": {"filename": re.compile(r'^.*.(cp,cps)$', re.IGNORECASE),"content":None,},
    "cplint": {"filename": re.compile(r'^.*.(P,cpl,ecl,lpad,pl,pro,prolog)$', re.IGNORECASE),"content":None,},
    "cpp": {"filename": re.compile(r'^.*.(C,CPP,H,c\+\+,cc,cp,cpp,cxx,h\+\+,hh,hpp,hxx,tpp)$', re.IGNORECASE),"content":None,},
    "cpp-objdump": {"filename": re.compile(r'^.*.(c\+\+-objdump,cpp-objdump,cxx-objdump)$', re.IGNORECASE),"content":None,},
    "cpsa": {"filename": re.compile(r'^.*.(cpsa)$', re.IGNORECASE),"content":None,},
    "cr": {"filename": re.compile(r'^.*.(cr)$', re.IGNORECASE),"content":None,},
    "crmsh": {"filename": re.compile(r'^.*.(crmsh,pcmk)$', re.IGNORECASE),"content":None,},
    "croc": {"filename": re.compile(r'^.*.(croc)$', re.IGNORECASE),"content":None,},
    "cry": {"filename": re.compile(r'^.*.(cry)$', re.IGNORECASE),"content":None,},
    "cryptol": {"filename": re.compile(r'^.*.(cry)$', re.IGNORECASE),"content":None,},
    "crystal": {"filename": re.compile(r'^.*.(cr)$', re.IGNORECASE),"content":None,},
    "cs": {"filename": re.compile(r'^.*.(cs)$', re.IGNORECASE),"content":None,},
    "csh": {"filename": re.compile(r'^.*.(csh,tcsh)$', re.IGNORECASE),"content":None,},
    "csharp": {"filename": re.compile(r'^.*.(cs)$', re.IGNORECASE),"content":None,},
    "csound": {"filename": re.compile(r'^.*.(orc,udo)$', re.IGNORECASE),"content":None,},
    "csound-csd": {"filename": re.compile(r'^.*.(csd)$', re.IGNORECASE),"content":None,},
    "csound-document": {"filename": re.compile(r'^.*.(csd)$', re.IGNORECASE),"content":None,},
    "csound-orc": {"filename": re.compile(r'^.*.(orc,udo)$', re.IGNORECASE),"content":None,},
    "csound-sco": {"filename": re.compile(r'^.*.(sco)$', re.IGNORECASE),"content":None,},
    "csound-score": {"filename": re.compile(r'^.*.(sco)$', re.IGNORECASE),"content":None,},
    "css": {"filename": re.compile(r'^.*.(css)$', re.IGNORECASE),"content":None,},
    "css+django": {"filename": re.compile(r'^.*.(css.j2,css.jinja2)$', re.IGNORECASE),"content":None,},
    "css+jinja": {"filename": re.compile(r'^.*.(css.j2,css.jinja2)$', re.IGNORECASE),"content":None,},
    "css+mozpreproc": {"filename": re.compile(r'^.*.(css.in)$', re.IGNORECASE),"content":None,},
    "css+ul4": {"filename": re.compile(r'^.*.(cssul4)$', re.IGNORECASE),"content":None,},
    "cu": {"filename": re.compile(r'^.*.(cu,cuh)$', re.IGNORECASE),"content":None,},
    "cucumber": {"filename": re.compile(r'^.*.(feature)$', re.IGNORECASE),"content":None,},
    "cuda": {"filename": re.compile(r'^.*.(cu,cuh)$', re.IGNORECASE),"content":None,},
    "cxx-objdump": {"filename": re.compile(r'^.*.(c\+\+-objdump,cpp-objdump,cxx-objdump)$', re.IGNORECASE),"content":None,},
    "cypher": {"filename": re.compile(r'^.*.(cyp,cypher)$', re.IGNORECASE),"content":None,},
    "cython": {"filename": re.compile(r'^.*.(pxd,pxi,pyx)$', re.IGNORECASE),"content":None,},
    "d": {"filename": re.compile(r'^.*.(d,di)$', re.IGNORECASE),"content":None,},
    "d-objdump": {"filename": re.compile(r'^.*.(d-objdump)$', re.IGNORECASE),"content":None,},
    "dart": {"filename": re.compile(r'^.*.(dart)$', re.IGNORECASE),"content":None,},
    "dasm16": {"filename": re.compile(r'^.*.(dasm,dasm16)$', re.IGNORECASE),"content":None,},
    "dax": {"filename": re.compile(r'^.*.(dax)$', re.IGNORECASE),"content":None,},
    "debian.sources": {"filename": re.compile(r'^.*.(sources)$', re.IGNORECASE),"content":None,},
    "delphi": {"filename": re.compile(r'^.*.(dpr,pas)$', re.IGNORECASE),"content":None,},
    "desktop": {"filename": re.compile(r'^.*.(desktop)$', re.IGNORECASE),"content":None,},
    "devicetree": {"filename": re.compile(r'^.*.(dts,dtsi)$', re.IGNORECASE),"content":None,},
    "dg": {"filename": re.compile(r'^.*.(dg)$', re.IGNORECASE),"content":None,},
    "diff": {"filename": re.compile(r'^.*.(diff,patch)$', re.IGNORECASE),"content":None,},
    "dmesg": {"filename": re.compile(r'^.*.(dmesg,kmsg)$', re.IGNORECASE),"content":None,},
    "do": {"filename": re.compile(r'^.*.(ado,do)$', re.IGNORECASE),"content":None,},
    "docker": {"filename": re.compile(r'^.*.(docker)$', re.IGNORECASE),"content":None,},
    "dockerfile": {"filename": re.compile(r'^.*.(docker)$', re.IGNORECASE),"content":None,},
    "dosbatch": {"filename": re.compile(r'^.*.(bat,cmd)$', re.IGNORECASE),"content":None,},
    "dosini": {"filename": re.compile(r'^.*.(cfg,inf,ini)$', re.IGNORECASE),"content":None,},
    "dot": {"filename": re.compile(r'^.*.(dot,gv)$', re.IGNORECASE),"content":None,},
    "dpatch": {"filename": re.compile(r'^.*.(darcspatch,dpatch)$', re.IGNORECASE),"content":None,},
    "dtd": {"filename": re.compile(r'^.*.(dtd)$', re.IGNORECASE),"content":None,},
    "dts": {"filename": re.compile(r'^.*.(dts,dtsi)$', re.IGNORECASE),"content":None,},
    "duby": {"filename": re.compile(r'^.*.(duby,gemspec,rake,rb,rbw,rbx)$', re.IGNORECASE),"content":None,},
    "duel": {"filename": re.compile(r'^.*.(duel,jbst)$', re.IGNORECASE),"content":None,},
    "dylan": {"filename": re.compile(r'^.*.(dyl,dylan,intr)$', re.IGNORECASE),"content":None,},
    "dylan-console": {"filename": re.compile(r'^.*.(dylan-console)$', re.IGNORECASE),"content":None,},
    "dylan-lid": {"filename": re.compile(r'^.*.(hdp,lid)$', re.IGNORECASE),"content":None,},
    "dylan-repl": {"filename": re.compile(r'^.*.(dylan-console)$', re.IGNORECASE),"content":None,},
    "earl-grey": {"filename": re.compile(r'^.*.(eg)$', re.IGNORECASE),"content":None,},
    "earlgrey": {"filename": re.compile(r'^.*.(eg)$', re.IGNORECASE),"content":None,},
    "easytrieve": {"filename": re.compile(r'^.*.(ezt,mac)$', re.IGNORECASE),"content":None,},
    "ebnf": {"filename": re.compile(r'^.*.(ebnf)$', re.IGNORECASE),"content":None,},
    "ec": {"filename": re.compile(r'^.*.(ec,eh)$', re.IGNORECASE),"content":None,},
    "ecl": {"filename": re.compile(r'^.*.(ecl)$', re.IGNORECASE),"content":None,},
    "eg": {"filename": re.compile(r'^.*.(eg)$', re.IGNORECASE),"content":None,},
    "eiffel": {"filename": re.compile(r'^.*.(e)$', re.IGNORECASE),"content":None,},
    "elisp": {"filename": re.compile(r'^.*.(el)$', re.IGNORECASE),"content":None,},
    "elixir": {"filename": re.compile(r'^.*.(eex,ex,exs,leex)$', re.IGNORECASE),"content":None,},
    "elm": {"filename": re.compile(r'^.*.(elm)$', re.IGNORECASE),"content":None,},
    "elpi": {"filename": re.compile(r'^.*.(elpi)$', re.IGNORECASE),"content":None,},
    "emacs": {"filename": re.compile(r'^.*.(el)$', re.IGNORECASE),"content":None,},
    "emacs-lisp": {"filename": re.compile(r'^.*.(el)$', re.IGNORECASE),"content":None,},
    "email": {"filename": re.compile(r'^.*.(eml)$', re.IGNORECASE),"content":None,},
    "eml": {"filename": re.compile(r'^.*.(eml)$', re.IGNORECASE),"content":None,},
    "erl": {"filename": re.compile(r'^.*.(erl-sh)$', re.IGNORECASE),"content":None,},
    "erlang": {"filename": re.compile(r'^.*.(erl,es,escript,hrl)$', re.IGNORECASE),"content":None,},
    "evoque": {"filename": re.compile(r'^.*.(evoque)$', re.IGNORECASE),"content":None,},
    "ex": {"filename": re.compile(r'^.*.(eex,ex,exs,leex)$', re.IGNORECASE),"content":None,},
    "execline": {"filename": re.compile(r'^.*.(exec)$', re.IGNORECASE),"content":None,},
    "exs": {"filename": re.compile(r'^.*.(eex,ex,exs,leex)$', re.IGNORECASE),"content":None,},
    "extempore": {"filename": re.compile(r'^.*.(xtm)$', re.IGNORECASE),"content":None,},
    "ezhil": {"filename": re.compile(r'^.*.(n)$', re.IGNORECASE),"content":None,},
    "f#": {"filename": re.compile(r'^.*.(fs,fsi,fsx)$', re.IGNORECASE),"content":None,},
    "f90": {"filename": re.compile(r'^.*.(F03,F90,f03,f90)$', re.IGNORECASE),"content":None,},
    "factor": {"filename": re.compile(r'^.*.(factor)$', re.IGNORECASE),"content":None,},
    "fan": {"filename": re.compile(r'^.*.(fan)$', re.IGNORECASE),"content":None,},
    "fancy": {"filename": re.compile(r'^.*.(fancypack,fy)$', re.IGNORECASE),"content":None,},
    "fc": {"filename": re.compile(r'^.*.(fc,func)$', re.IGNORECASE),"content":None,},
    "felix": {"filename": re.compile(r'^.*.(flx,flxh)$', re.IGNORECASE),"content":None,},
    "fennel": {"filename": re.compile(r'^.*.(fnl)$', re.IGNORECASE),"content":None,},
    "fif": {"filename": re.compile(r'^.*.(fif)$', re.IGNORECASE),"content":None,},
    "fift": {"filename": re.compile(r'^.*.(fif)$', re.IGNORECASE),"content":None,},
    "fish": {"filename": re.compile(r'^.*.(fish,load)$', re.IGNORECASE),"content":None,},
    "fishshell": {"filename": re.compile(r'^.*.(fish,load)$', re.IGNORECASE),"content":None,},
    "flo": {"filename": re.compile(r'^.*.(flo)$', re.IGNORECASE),"content":None,},
    "floscript": {"filename": re.compile(r'^.*.(flo)$', re.IGNORECASE),"content":None,},
    "flx": {"filename": re.compile(r'^.*.(flx,flxh)$', re.IGNORECASE),"content":None,},
    "fnl": {"filename": re.compile(r'^.*.(fnl)$', re.IGNORECASE),"content":None,},
    "forth": {"filename": re.compile(r'^.*.(frt,fs)$', re.IGNORECASE),"content":None,},
    "fortran": {"filename": re.compile(r'^.*.(F03,F90,f03,f90)$', re.IGNORECASE),"content":None,},
    "fortranfixed": {"filename": re.compile(r'^.*.(F,f)$', re.IGNORECASE),"content":None,},
    "foxpro": {"filename": re.compile(r'^.*.(PRG,prg)$', re.IGNORECASE),"content":None,},
    "freefem": {"filename": re.compile(r'^.*.(edp)$', re.IGNORECASE),"content":None,},
    "fsharp": {"filename": re.compile(r'^.*.(fs,fsi,fsx)$', re.IGNORECASE),"content":None,},
    "fstar": {"filename": re.compile(r'^.*.(fst,fsti)$', re.IGNORECASE),"content":None,},
    "func": {"filename": re.compile(r'^.*.(fc,func)$', re.IGNORECASE),"content":None,},
    "futhark": {"filename": re.compile(r'^.*.(fut)$', re.IGNORECASE),"content":None,},
    "fy": {"filename": re.compile(r'^.*.(fancypack,fy)$', re.IGNORECASE),"content":None,},
    "gap": {"filename": re.compile(r'^.*.(g,gap,gd,gi)$', re.IGNORECASE),"content":None,},
    "gap-console": {"filename": re.compile(r'^.*.(tst)$', re.IGNORECASE),"content":None,},
    "gap-repl": {"filename": re.compile(r'^.*.(tst)$', re.IGNORECASE),"content":None,},
    "gas": {"filename": re.compile(r'^.*.(S,s)$', re.IGNORECASE),"content":None,},
    "gawk": {"filename": re.compile(r'^.*.(awk)$', re.IGNORECASE),"content":None,},
    "gcode": {"filename": re.compile(r'^.*.(gcode)$', re.IGNORECASE),"content":None,},
    "gd": {"filename": re.compile(r'^.*.(gd)$', re.IGNORECASE),"content":None,},
    "gdscript": {"filename": re.compile(r'^.*.(gd)$', re.IGNORECASE),"content":None,},
    "genshi": {"filename": re.compile(r'^.*.(kid)$', re.IGNORECASE),"content":None,},
    "gherkin": {"filename": re.compile(r'^.*.(feature)$', re.IGNORECASE),"content":None,},
    "gleam": {"filename": re.compile(r'^.*.(gleam)$', re.IGNORECASE),"content":None,},
    "glsl": {"filename": re.compile(r'^.*.(frag,geo,vert)$', re.IGNORECASE),"content":None,},
    "gnuplot": {"filename": re.compile(r'^.*.(plot,plt)$', re.IGNORECASE),"content":None,},
    "go": {"filename": re.compile(r'^.*.(go)$', re.IGNORECASE),"content":None,},
    "golang": {"filename": re.compile(r'^.*.(go)$', re.IGNORECASE),"content":None,},
    "golo": {"filename": re.compile(r'^.*.(golo)$', re.IGNORECASE),"content":None,},
    "gooddata-cl": {"filename": re.compile(r'^.*.(gdc)$', re.IGNORECASE),"content":None,},
    "googlesql": {"filename": re.compile(r'^.*.(googlesql,googlesql.sql)$', re.IGNORECASE),"content":None,},
    "gosu": {"filename": re.compile(r'^.*.(gs,gsp,gsx,vark)$', re.IGNORECASE),"content":None,},
    "graphql": {"filename": re.compile(r'^.*.(graphql)$', re.IGNORECASE),"content":None,},
    "graphviz": {"filename": re.compile(r'^.*.(dot,gv)$', re.IGNORECASE),"content":None,},
    "groff": {"filename": re.compile(r'^.*.(1p,3pm,[1-9],man)$', re.IGNORECASE),"content":None,},
    "groovy": {"filename": re.compile(r'^.*.(gradle,groovy)$', re.IGNORECASE),"content":None,},
    "gsed": {"filename": re.compile(r'^.*.([gs]sed,sed)$', re.IGNORECASE),"content":None,},
    "gsql": {"filename": re.compile(r'^.*.(gsql)$', re.IGNORECASE),"content":None,},
    "gst": {"filename": re.compile(r'^.*.(gst)$', re.IGNORECASE),"content":None,},
    "haml": {"filename": re.compile(r'^.*.(haml)$', re.IGNORECASE),"content":None,},
    "hare": {"filename": re.compile(r'^.*.(ha)$', re.IGNORECASE),"content":None,},
    "haskell": {"filename": re.compile(r'^.*.(hs)$', re.IGNORECASE),"content":None,},
    "haxe": {"filename": re.compile(r'^.*.(hx,hxsl)$', re.IGNORECASE),"content":None,},
    "haxeml": {"filename": re.compile(r'^.*.(hxml)$', re.IGNORECASE),"content":None,},
    "hcl": {"filename": re.compile(r'^.*.(hcl,tf)$', re.IGNORECASE),"content":None,},
    "hlsl": {"filename": re.compile(r'^.*.(hlsl,hlsli)$', re.IGNORECASE),"content":None,},
    "hs": {"filename": re.compile(r'^.*.(hs)$', re.IGNORECASE),"content":None,},
    "hsa": {"filename": re.compile(r'^.*.(hsail)$', re.IGNORECASE),"content":None,},
    "hsail": {"filename": re.compile(r'^.*.(hsail)$', re.IGNORECASE),"content":None,},
    "html": {"filename": re.compile(r'^.*.(htm,html,xhtml,xslt)$', re.IGNORECASE),"content":None,},
    "html+django": {"filename": re.compile(r'^.*.(htm.j2,htm.jinja2,html.j2,html.jinja2,xhtml.j2,xhtml.jinja2)$', re.IGNORECASE),"content":None,},
    "html+erb": {"filename": re.compile(r'^.*.(rhtml)$', re.IGNORECASE),"content":None,},
    "html+handlebars": {"filename": re.compile(r'^.*.(handlebars,hbs)$', re.IGNORECASE),"content":None,},
    "html+jinja": {"filename": re.compile(r'^.*.(htm.j2,htm.jinja2,html.j2,html.jinja2,xhtml.j2,xhtml.jinja2)$', re.IGNORECASE),"content":None,},
    "html+ng2": {"filename": re.compile(r'^.*.(ng2)$', re.IGNORECASE),"content":None,},
    "html+php": {"filename": re.compile(r'^.*.(phtml)$', re.IGNORECASE),"content":None,},
    "html+ruby": {"filename": re.compile(r'^.*.(rhtml)$', re.IGNORECASE),"content":None,},
    "html+twig": {"filename": re.compile(r'^.*.(twig)$', re.IGNORECASE),"content":None,},
    "html+ul4": {"filename": re.compile(r'^.*.(htmlul4)$', re.IGNORECASE),"content":None,},
    "htmldjango": {"filename": re.compile(r'^.*.(htm.j2,htm.jinja2,html.j2,html.jinja2,xhtml.j2,xhtml.jinja2)$', re.IGNORECASE),"content":None,},
    "hx": {"filename": re.compile(r'^.*.(hx,hxsl)$', re.IGNORECASE),"content":None,},
    "hxml": {"filename": re.compile(r'^.*.(hxml)$', re.IGNORECASE),"content":None,},
    "hxsl": {"filename": re.compile(r'^.*.(hx,hxsl)$', re.IGNORECASE),"content":None,},
    "hy": {"filename": re.compile(r'^.*.(hy)$', re.IGNORECASE),"content":None,},
    "hybris": {"filename": re.compile(r'^.*.(hyb)$', re.IGNORECASE),"content":None,},
    "hylang": {"filename": re.compile(r'^.*.(hy)$', re.IGNORECASE),"content":None,},
    "i6": {"filename": re.compile(r'^.*.(inf)$', re.IGNORECASE),"content":None,},
    "i6t": {"filename": re.compile(r'^.*.(i6t)$', re.IGNORECASE),"content":None,},
    "i7": {"filename": re.compile(r'^.*.(i7x,ni)$', re.IGNORECASE),"content":None,},
    "icon": {"filename": re.compile(r'^.*.(ICON,icon)$', re.IGNORECASE),"content":None,},
    "idl": {"filename": re.compile(r'^.*.(pro)$', re.IGNORECASE),"content":None,},
    "idl4": {"filename": re.compile(r'^.*.(camkes,idl4)$', re.IGNORECASE),"content":None,},
    "idr": {"filename": re.compile(r'^.*.(idr)$', re.IGNORECASE),"content":None,},
    "idris": {"filename": re.compile(r'^.*.(idr)$', re.IGNORECASE),"content":None,},
    "igor": {"filename": re.compile(r'^.*.(ipf)$', re.IGNORECASE),"content":None,},
    "igorpro": {"filename": re.compile(r'^.*.(ipf)$', re.IGNORECASE),"content":None,},
    "ik": {"filename": re.compile(r'^.*.(ik)$', re.IGNORECASE),"content":None,},
    "inform6": {"filename": re.compile(r'^.*.(inf)$', re.IGNORECASE),"content":None,},
    "inform7": {"filename": re.compile(r'^.*.(i7x,ni)$', re.IGNORECASE),"content":None,},
    "ini": {"filename": re.compile(r'^.*.(cfg,inf,ini)$', re.IGNORECASE),"content":None,},
    "io": {"filename": re.compile(r'^.*.(io)$', re.IGNORECASE),"content":None,},
    "ioke": {"filename": re.compile(r'^.*.(ik)$', re.IGNORECASE),"content":None,},
    "ipython": {"filename": re.compile(r'^.*.(bzl,jy,py,pyi,pyw,sage,sc,tac)$', re.IGNORECASE),"content":None,},
    "ipython3": {"filename": re.compile(r'^.*.(bzl,jy,py,pyi,pyw,sage,sc,tac)$', re.IGNORECASE),"content":None,},
    "irc": {"filename": re.compile(r'^.*.(weechatlog)$', re.IGNORECASE),"content":None,},
    "isabelle": {"filename": re.compile(r'^.*.(thy)$', re.IGNORECASE),"content":None,},
    "j": {"filename": re.compile(r'^.*.(ijs)$', re.IGNORECASE),"content":None,},
    "jade": {"filename": re.compile(r'^.*.(jade,pug)$', re.IGNORECASE),"content":None,},
    "jags": {"filename": re.compile(r'^.*.(bug,jag)$', re.IGNORECASE),"content":None,},
    "janet": {"filename": re.compile(r'^.*.(janet,jdn)$', re.IGNORECASE),"content":None,},
    "jasmin": {"filename": re.compile(r'^.*.(j)$', re.IGNORECASE),"content":None,},
    "jasminxt": {"filename": re.compile(r'^.*.(j)$', re.IGNORECASE),"content":None,},
    "java": {"filename": re.compile(r'^.*.(java)$', re.IGNORECASE),"content":None,},
    "javascript": {"filename": re.compile(r'^.*.(cjs,js,jsm,mjs)$', re.IGNORECASE),"content":None,},
    "javascript+django": {"filename": re.compile(r'^.*.(js.j2,js.jinja2)$', re.IGNORECASE),"content":None,},
    "javascript+jinja": {"filename": re.compile(r'^.*.(js.j2,js.jinja2)$', re.IGNORECASE),"content":None,},
    "javascript+mozpreproc": {"filename": re.compile(r'^.*.(js.in)$', re.IGNORECASE),"content":None,},
    "jbst": {"filename": re.compile(r'^.*.(duel,jbst)$', re.IGNORECASE),"content":None,},
    "jcl": {"filename": re.compile(r'^.*.(jcl)$', re.IGNORECASE),"content":None,},
    "jl": {"filename": re.compile(r'^.*.(jl)$', re.IGNORECASE),"content":None,},
    "jmespath": {"filename": re.compile(r'^.*.(jp)$', re.IGNORECASE),"content":None,},
    "jp": {"filename": re.compile(r'^.*.(jp)$', re.IGNORECASE),"content":None,},
    "jproperties": {"filename": re.compile(r'^.*.(properties)$', re.IGNORECASE),"content":None,},
    "js": {"filename": re.compile(r'^.*.(cjs,js,jsm,mjs)$', re.IGNORECASE),"content":None,},
    "js+django": {"filename": re.compile(r'^.*.(js.j2,js.jinja2)$', re.IGNORECASE),"content":None,},
    "js+jinja": {"filename": re.compile(r'^.*.(js.j2,js.jinja2)$', re.IGNORECASE),"content":None,},
    "js+ul4": {"filename": re.compile(r'^.*.(jsul4)$', re.IGNORECASE),"content":None,},
    "jsgf": {"filename": re.compile(r'^.*.(jsgf)$', re.IGNORECASE),"content":None,},
    "jslt": {"filename": re.compile(r'^.*.(jslt)$', re.IGNORECASE),"content":None,},
    "json": {"filename": re.compile(r'^.*.(json,jsonl,ndjson)$', re.IGNORECASE),"content":None,},
    "json-ld": {"filename": re.compile(r'^.*.(jsonld)$', re.IGNORECASE),"content":None,},
    "json-object": {"filename": re.compile(r'^.*.(json,jsonl,ndjson)$', re.IGNORECASE),"content":None,},
    "json5": {"filename": re.compile(r'^.*.(json5)$', re.IGNORECASE),"content":None,},
    "jsonld": {"filename": re.compile(r'^.*.(jsonld)$', re.IGNORECASE),"content":None,},
    "jsonml+bst": {"filename": re.compile(r'^.*.(duel,jbst)$', re.IGNORECASE),"content":None,},
    "jsonnet": {"filename": re.compile(r'^.*.(jsonnet,libsonnet)$', re.IGNORECASE),"content":None,},
    "jsp": {"filename": re.compile(r'^.*.(jsp)$', re.IGNORECASE),"content":None,},
    "jsx": {"filename": re.compile(r'^.*.(jsx,react)$', re.IGNORECASE),"content":None,},
    "julia": {"filename": re.compile(r'^.*.(jl)$', re.IGNORECASE),"content":None,},
    "juttle": {"filename": re.compile(r'^.*.(juttle)$', re.IGNORECASE),"content":None,},
    "k": {"filename": re.compile(r'^.*.(k)$', re.IGNORECASE),"content":None,},
    "kal": {"filename": re.compile(r'^.*.(kal)$', re.IGNORECASE),"content":None,},
    "kid": {"filename": re.compile(r'^.*.(kid)$', re.IGNORECASE),"content":None,},
    "kmsg": {"filename": re.compile(r'^.*.(dmesg,kmsg)$', re.IGNORECASE),"content":None,},
    "koka": {"filename": re.compile(r'^.*.(kk,kki)$', re.IGNORECASE),"content":None,},
    "kotlin": {"filename": re.compile(r'^.*.(kt,kts)$', re.IGNORECASE),"content":None,},
    "kql": {"filename": re.compile(r'^.*.(kql,kusto)$', re.IGNORECASE),"content":None,},
    "ksh": {"filename": re.compile(r'^.*.(bash,ebuild,eclass,exheres-0,exlib,ksh,sh,zsh)$', re.IGNORECASE),"content":None,},
    "kuin": {"filename": re.compile(r'^.*.(kn)$', re.IGNORECASE),"content":None,},
    "kusto": {"filename": re.compile(r'^.*.(kql,kusto)$', re.IGNORECASE),"content":None,},
    "lagda": {"filename": re.compile(r'^.*.(lagda)$', re.IGNORECASE),"content":None,},
    "lasso": {"filename": re.compile(r'^.*.(lasso,lasso[89])$', re.IGNORECASE),"content":None,},
    "lassoscript": {"filename": re.compile(r'^.*.(lasso,lasso[89])$', re.IGNORECASE),"content":None,},
    "latex": {"filename": re.compile(r'^.*.(aux,tex,toc)$', re.IGNORECASE),"content":None,},
    "lcry": {"filename": re.compile(r'^.*.(lcry)$', re.IGNORECASE),"content":None,},
    "lcryptol": {"filename": re.compile(r'^.*.(lcry)$', re.IGNORECASE),"content":None,},
    "ldif": {"filename": re.compile(r'^.*.(ldif)$', re.IGNORECASE),"content":None,},
    "lean": {"filename": re.compile(r'^.*.(lean)$', re.IGNORECASE),"content":None,},
    "lean3": {"filename": re.compile(r'^.*.(lean)$', re.IGNORECASE),"content":None,},
    "lean4": {"filename": re.compile(r'^.*.(lean)$', re.IGNORECASE),"content":None,},
    "less": {"filename": re.compile(r'^.*.(less)$', re.IGNORECASE),"content":None,},
    "lhaskell": {"filename": re.compile(r'^.*.(lhs)$', re.IGNORECASE),"content":None,},
    "lhs": {"filename": re.compile(r'^.*.(lhs)$', re.IGNORECASE),"content":None,},
    "lid": {"filename": re.compile(r'^.*.(hdp,lid)$', re.IGNORECASE),"content":None,},
    "lidr": {"filename": re.compile(r'^.*.(lidr)$', re.IGNORECASE),"content":None,},
    "lidris": {"filename": re.compile(r'^.*.(lidr)$', re.IGNORECASE),"content":None,},
    "lilypond": {"filename": re.compile(r'^.*.(ly)$', re.IGNORECASE),"content":None,},
    "limbo": {"filename": re.compile(r'^.*.(b)$', re.IGNORECASE),"content":None,},
    "liquid": {"filename": re.compile(r'^.*.(liquid)$', re.IGNORECASE),"content":None,},
    "lisp": {"filename": re.compile(r'^.*.(cl,lisp)$', re.IGNORECASE),"content":None,},
    "literate-agda": {"filename": re.compile(r'^.*.(lagda)$', re.IGNORECASE),"content":None,},
    "literate-cryptol": {"filename": re.compile(r'^.*.(lcry)$', re.IGNORECASE),"content":None,},
    "literate-haskell": {"filename": re.compile(r'^.*.(lhs)$', re.IGNORECASE),"content":None,},
    "literate-idris": {"filename": re.compile(r'^.*.(lidr)$', re.IGNORECASE),"content":None,},
    "live-script": {"filename": re.compile(r'^.*.(ls)$', re.IGNORECASE),"content":None,},
    "livescript": {"filename": re.compile(r'^.*.(ls)$', re.IGNORECASE),"content":None,},
    "llvm": {"filename": re.compile(r'^.*.(ll)$', re.IGNORECASE),"content":None,},
    "llvm-mir": {"filename": re.compile(r'^.*.(mir)$', re.IGNORECASE),"content":None,},
    "lobas": {"filename": re.compile(r'^.*.(bas,vb)$', re.IGNORECASE),"content":None,},
    "logos": {"filename": re.compile(r'^.*.(x,xi,xm,xmi)$', re.IGNORECASE),"content":None,},
    "logtalk": {"filename": re.compile(r'^.*.(lgt,logtalk)$', re.IGNORECASE),"content":None,},
    "lsl": {"filename": re.compile(r'^.*.(lsl)$', re.IGNORECASE),"content":None,},
    "lua": {"filename": re.compile(r'^.*.(lua,wlua)$', re.IGNORECASE),"content":None,},
    "luau": {"filename": re.compile(r'^.*.(luau)$', re.IGNORECASE),"content":None,},
    "m2": {"filename": re.compile(r'^.*.(def,mod)$', re.IGNORECASE),"content":None,},
    "macaulay2": {"filename": re.compile(r'^.*.(m2)$', re.IGNORECASE),"content":None,},
    "macsyma": {"filename": re.compile(r'^.*.(mac,max)$', re.IGNORECASE),"content":None,},
    "make": {"filename": re.compile(r'^.*.(mak,mk)$', re.IGNORECASE),"content":None,},
    "makefile": {"filename": re.compile(r'^.*.(mak,mk)$', re.IGNORECASE),"content":None,},
    "mako": {"filename": re.compile(r'^.*.(mao)$', re.IGNORECASE),"content":None,},
    "man": {"filename": re.compile(r'^.*.(1p,3pm,[1-9],man)$', re.IGNORECASE),"content":None,},
    "maple": {"filename": re.compile(r'^.*.(mi,mm,mpl)$', re.IGNORECASE),"content":None,},
    "maql": {"filename": re.compile(r'^.*.(maql)$', re.IGNORECASE),"content":None,},
    "markdown": {"filename": re.compile(r'^.*.(markdown,md)$', re.IGNORECASE),"content":None,},
    "mask": {"filename": re.compile(r'^.*.(mask)$', re.IGNORECASE),"content":None,},
    "mason": {"filename": re.compile(r'^.*.(m,mc,mhtml,mi)$', re.IGNORECASE),"content":None,},
    "mathematica": {"filename": re.compile(r'^.*.(cdf,ma,nb,nbp)$', re.IGNORECASE),"content":None,},
    "matlab": {"filename": re.compile(r'^.*.(m)$', re.IGNORECASE),"content":None,},
    "mawk": {"filename": re.compile(r'^.*.(awk)$', re.IGNORECASE),"content":None,},
    "maxima": {"filename": re.compile(r'^.*.(mac,max)$', re.IGNORECASE),"content":None,},
    "mcf": {"filename": re.compile(r'^.*.(mcfunction)$', re.IGNORECASE),"content":None,},
    "mcfunction": {"filename": re.compile(r'^.*.(mcfunction)$', re.IGNORECASE),"content":None,},
    "mcschema": {"filename": re.compile(r'^.*.(mcschema)$', re.IGNORECASE),"content":None,},
    "md": {"filename": re.compile(r'^.*.(markdown,md)$', re.IGNORECASE),"content":None,},
    "mf": {"filename": re.compile(r'^.*.(mak,mk)$', re.IGNORECASE),"content":None,},
    "miniscript": {"filename": re.compile(r'^.*.(ms)$', re.IGNORECASE),"content":None,},
    "mips": {"filename": re.compile(r'^.*.(MIPS,mips)$', re.IGNORECASE),"content":None,},
    "mma": {"filename": re.compile(r'^.*.(cdf,ma,nb,nbp)$', re.IGNORECASE),"content":None,},
    "modelica": {"filename": re.compile(r'^.*.(mo)$', re.IGNORECASE),"content":None,},
    "modula2": {"filename": re.compile(r'^.*.(def,mod)$', re.IGNORECASE),"content":None,},
    "mojo": {"filename": re.compile(r'^.*.(mojo,🔥)$', re.IGNORECASE),"content":None,},
    "monkey": {"filename": re.compile(r'^.*.(monkey)$', re.IGNORECASE),"content":None,},
    "monte": {"filename": re.compile(r'^.*.(mt)$', re.IGNORECASE),"content":None,},
    "moo": {"filename": re.compile(r'^.*.(moo)$', re.IGNORECASE),"content":None,},
    "moocode": {"filename": re.compile(r'^.*.(moo)$', re.IGNORECASE),"content":None,},
    "moon": {"filename": re.compile(r'^.*.(moon)$', re.IGNORECASE),"content":None,},
    "moonscript": {"filename": re.compile(r'^.*.(moon)$', re.IGNORECASE),"content":None,},
    "mosel": {"filename": re.compile(r'^.*.(mos)$', re.IGNORECASE),"content":None,},
    "mq4": {"filename": re.compile(r'^.*.(mq4,mq5,mqh)$', re.IGNORECASE),"content":None,},
    "mq5": {"filename": re.compile(r'^.*.(mq4,mq5,mqh)$', re.IGNORECASE),"content":None,},
    "mql": {"filename": re.compile(r'^.*.(mq4,mq5,mqh)$', re.IGNORECASE),"content":None,},
    "mql4": {"filename": re.compile(r'^.*.(mq4,mq5,mqh)$', re.IGNORECASE),"content":None,},
    "mql5": {"filename": re.compile(r'^.*.(mq4,mq5,mqh)$', re.IGNORECASE),"content":None,},
    "ms": {"filename": re.compile(r'^.*.(ms)$', re.IGNORECASE),"content":None,},
    "msc": {"filename": re.compile(r'^.*.(msc)$', re.IGNORECASE),"content":None,},
    "mscgen": {"filename": re.compile(r'^.*.(msc)$', re.IGNORECASE),"content":None,},
    "mupad": {"filename": re.compile(r'^.*.(mu)$', re.IGNORECASE),"content":None,},
    "mxml": {"filename": re.compile(r'^.*.(mxml)$', re.IGNORECASE),"content":None,},
    "myghty": {"filename": re.compile(r'^.*.(myt)$', re.IGNORECASE),"content":None,},
    "nasm": {"filename": re.compile(r'^.*.(ASM,asm,nasm)$', re.IGNORECASE),"content":None,},
    "nawk": {"filename": re.compile(r'^.*.(awk)$', re.IGNORECASE),"content":None,},
    "nb": {"filename": re.compile(r'^.*.(cdf,ma,nb,nbp)$', re.IGNORECASE),"content":None,},
    "ncl": {"filename": re.compile(r'^.*.(ncl)$', re.IGNORECASE),"content":None,},
    "nemerle": {"filename": re.compile(r'^.*.(n)$', re.IGNORECASE),"content":None,},
    "nesc": {"filename": re.compile(r'^.*.(nc)$', re.IGNORECASE),"content":None,},
    "nestedtext": {"filename": re.compile(r'^.*.(nt)$', re.IGNORECASE),"content":None,},
    "newlisp": {"filename": re.compile(r'^.*.(kif,lsp,nl)$', re.IGNORECASE),"content":None,},
    "newspeak": {"filename": re.compile(r'^.*.(ns2)$', re.IGNORECASE),"content":None,},
    "nim": {"filename": re.compile(r'^.*.(nim,nimrod)$', re.IGNORECASE),"content":None,},
    "nimrod": {"filename": re.compile(r'^.*.(nim,nimrod)$', re.IGNORECASE),"content":None,},
    "nit": {"filename": re.compile(r'^.*.(nit)$', re.IGNORECASE),"content":None,},
    "nix": {"filename": re.compile(r'^.*.(nix)$', re.IGNORECASE),"content":None,},
    "nixos": {"filename": re.compile(r'^.*.(nix)$', re.IGNORECASE),"content":None,},
    "nroff": {"filename": re.compile(r'^.*.(1p,3pm,[1-9],man)$', re.IGNORECASE),"content":None,},
    "nsh": {"filename": re.compile(r'^.*.(nsh,nsi)$', re.IGNORECASE),"content":None,},
    "nsi": {"filename": re.compile(r'^.*.(nsh,nsi)$', re.IGNORECASE),"content":None,},
    "nsis": {"filename": re.compile(r'^.*.(nsh,nsi)$', re.IGNORECASE),"content":None,},
    "nt": {"filename": re.compile(r'^.*.(nt)$', re.IGNORECASE),"content":None,},
    "numba_ir": {"filename": re.compile(r'^.*.(numba_ir)$', re.IGNORECASE),"content":None,},
    "numbair": {"filename": re.compile(r'^.*.(numba_ir)$', re.IGNORECASE),"content":None,},
    "nusmv": {"filename": re.compile(r'^.*.(smv)$', re.IGNORECASE),"content":None,},
    "obj-c": {"filename": re.compile(r'^.*.(h,m)$', re.IGNORECASE),"content":None,},
    "obj-c++": {"filename": re.compile(r'^.*.(hh,mm)$', re.IGNORECASE),"content":None,},
    "obj-j": {"filename": re.compile(r'^.*.(j)$', re.IGNORECASE),"content":None,},
    "objc": {"filename": re.compile(r'^.*.(h,m)$', re.IGNORECASE),"content":None,},
    "objc++": {"filename": re.compile(r'^.*.(hh,mm)$', re.IGNORECASE),"content":None,},
    "objdump": {"filename": re.compile(r'^.*.(objdump)$', re.IGNORECASE),"content":None,},
    "objdump-nasm": {"filename": re.compile(r'^.*.(objdump-intel)$', re.IGNORECASE),"content":None,},
    "objective-c": {"filename": re.compile(r'^.*.(h,m)$', re.IGNORECASE),"content":None,},
    "objective-c++": {"filename": re.compile(r'^.*.(hh,mm)$', re.IGNORECASE),"content":None,},
    "objective-j": {"filename": re.compile(r'^.*.(j)$', re.IGNORECASE),"content":None,},
    "objectivec": {"filename": re.compile(r'^.*.(h,m)$', re.IGNORECASE),"content":None,},
    "objectivec++": {"filename": re.compile(r'^.*.(hh,mm)$', re.IGNORECASE),"content":None,},
    "objectivej": {"filename": re.compile(r'^.*.(j)$', re.IGNORECASE),"content":None,},
    "objectpascal": {"filename": re.compile(r'^.*.(dpr,pas)$', re.IGNORECASE),"content":None,},
    "objj": {"filename": re.compile(r'^.*.(j)$', re.IGNORECASE),"content":None,},
    "ocaml": {"filename": re.compile(r'^.*.(ml,mli,mll,mly)$', re.IGNORECASE),"content":None,},
    "octave": {"filename": re.compile(r'^.*.(m)$', re.IGNORECASE),"content":None,},
    "odin": {"filename": re.compile(r'^.*.(odin)$', re.IGNORECASE),"content":None,},
    "omg-idl": {"filename": re.compile(r'^.*.(idl,pidl)$', re.IGNORECASE),"content":None,},
    "oobas": {"filename": re.compile(r'^.*.(bas,vb)$', re.IGNORECASE),"content":None,},
    "ooc": {"filename": re.compile(r'^.*.(ooc)$', re.IGNORECASE),"content":None,},
    "opa": {"filename": re.compile(r'^.*.(opa)$', re.IGNORECASE),"content":None,},
    "openbugs": {"filename": re.compile(r'^.*.(bug)$', re.IGNORECASE),"content":None,},
    "openedge": {"filename": re.compile(r'^.*.(cls,p)$', re.IGNORECASE),"content":None,},
    "openrc": {"filename": re.compile(r'^.*.(bash,ebuild,eclass,exheres-0,exlib,ksh,sh,zsh)$', re.IGNORECASE),"content":None,},
    "openscad": {"filename": re.compile(r'^.*.(scad)$', re.IGNORECASE),"content":None,},
    "org": {"filename": re.compile(r'^.*.(org)$', re.IGNORECASE),"content":None,},
    "org-mode": {"filename": re.compile(r'^.*.(org)$', re.IGNORECASE),"content":None,},
    "orgmode": {"filename": re.compile(r'^.*.(org)$', re.IGNORECASE),"content":None,},
    "pan": {"filename": re.compile(r'^.*.(pan)$', re.IGNORECASE),"content":None,},
    "parasail": {"filename": re.compile(r'^.*.(psi,psl)$', re.IGNORECASE),"content":None,},
    "pas": {"filename": re.compile(r'^.*.(dpr,pas)$', re.IGNORECASE),"content":None,},
    "pascal": {"filename": re.compile(r'^.*.(dpr,pas)$', re.IGNORECASE),"content":None,},
    "pawn": {"filename": re.compile(r'^.*.(inc,p,pwn)$', re.IGNORECASE),"content":None,},
    "pcmk": {"filename": re.compile(r'^.*.(crmsh,pcmk)$', re.IGNORECASE),"content":None,},
    "pddl": {"filename": re.compile(r'^.*.(pddl)$', re.IGNORECASE),"content":None,},
    "peg": {"filename": re.compile(r'^.*.(peg)$', re.IGNORECASE),"content":None,},
    "pem": {"filename": re.compile(r'^.*.(asc,pem)$', re.IGNORECASE),"content":None,},
    "perl": {"filename": re.compile(r'^.*.(perl,pl,pm,t)$', re.IGNORECASE),"content":None,},
    "perl6": {"filename": re.compile(r'^.*.(6pl,6pm,nqp,p6,p6l,p6m,pl,pl6,pm,pm6,raku,rakudoc,rakumod,rakutest,t)$', re.IGNORECASE),"content":None,},
    "phix": {"filename": re.compile(r'^.*.(exw)$', re.IGNORECASE),"content":None,},
    "php": {"filename": re.compile(r'^.*.(inc,php,php[345])$', re.IGNORECASE),"content":None,},
    "php3": {"filename": re.compile(r'^.*.(inc,php,php[345])$', re.IGNORECASE),"content":None,},
    "php4": {"filename": re.compile(r'^.*.(inc,php,php[345])$', re.IGNORECASE),"content":None,},
    "php5": {"filename": re.compile(r'^.*.(inc,php,php[345])$', re.IGNORECASE),"content":None,},
    "pig": {"filename": re.compile(r'^.*.(pig)$', re.IGNORECASE),"content":None,},
    "pike": {"filename": re.compile(r'^.*.(pike,pmod)$', re.IGNORECASE),"content":None,},
    "pkgconfig": {"filename": re.compile(r'^.*.(pc)$', re.IGNORECASE),"content":None,},
    "pl": {"filename": re.compile(r'^.*.(perl,pl,pm,t)$', re.IGNORECASE),"content":None,},
    "pl6": {"filename": re.compile(r'^.*.(6pl,6pm,nqp,p6,p6l,p6m,pl,pl6,pm,pm6,raku,rakudoc,rakumod,rakutest,t)$', re.IGNORECASE),"content":None,},
    "po": {"filename": re.compile(r'^.*.(po,pot)$', re.IGNORECASE),"content":None,},
    "pointless": {"filename": re.compile(r'^.*.(ptls)$', re.IGNORECASE),"content":None,},
    "pony": {"filename": re.compile(r'^.*.(pony)$', re.IGNORECASE),"content":None,},
    "portugol": {"filename": re.compile(r'^.*.(alg,portugol)$', re.IGNORECASE),"content":None,},
    "posh": {"filename": re.compile(r'^.*.(ps1,psm1)$', re.IGNORECASE),"content":None,},
    "postgres-explain": {"filename": re.compile(r'^.*.(explain)$', re.IGNORECASE),"content":None,},
    "postscr": {"filename": re.compile(r'^.*.(eps,ps)$', re.IGNORECASE),"content":None,},
    "postscript": {"filename": re.compile(r'^.*.(eps,ps)$', re.IGNORECASE),"content":None,},
    "pot": {"filename": re.compile(r'^.*.(po,pot)$', re.IGNORECASE),"content":None,},
    "pov": {"filename": re.compile(r'^.*.(inc,pov)$', re.IGNORECASE),"content":None,},
    "powershell": {"filename": re.compile(r'^.*.(ps1,psm1)$', re.IGNORECASE),"content":None,},
    "praat": {"filename": re.compile(r'^.*.(praat,proc,psc)$', re.IGNORECASE),"content":None,},
    "progress": {"filename": re.compile(r'^.*.(cls,p)$', re.IGNORECASE),"content":None,},
    "prolog": {"filename": re.compile(r'^.*.(ecl,pl,pro,prolog)$', re.IGNORECASE),"content":None,},
    "promela": {"filename": re.compile(r'^.*.(pm,pml,pr,prm,prom,promela)$', re.IGNORECASE),"content":None,},
    "promql": {"filename": re.compile(r'^.*.(promql)$', re.IGNORECASE),"content":None,},
    "properties": {"filename": re.compile(r'^.*.(properties)$', re.IGNORECASE),"content":None,},
    "proto": {"filename": re.compile(r'^.*.(proto)$', re.IGNORECASE),"content":None,},
    "protobuf": {"filename": re.compile(r'^.*.(proto)$', re.IGNORECASE),"content":None,},
    "prql": {"filename": re.compile(r'^.*.(prql)$', re.IGNORECASE),"content":None,},
    "ps1": {"filename": re.compile(r'^.*.(ps1,psm1)$', re.IGNORECASE),"content":None,},
    "psm1": {"filename": re.compile(r'^.*.(ps1,psm1)$', re.IGNORECASE),"content":None,},
    "ptx": {"filename": re.compile(r'^.*.(ptx)$', re.IGNORECASE),"content":None,},
    "pug": {"filename": re.compile(r'^.*.(jade,pug)$', re.IGNORECASE),"content":None,},
    "puppet": {"filename": re.compile(r'^.*.(pp)$', re.IGNORECASE),"content":None,},
    "pwsh": {"filename": re.compile(r'^.*.(ps1,psm1)$', re.IGNORECASE),"content":None,},
    "py": {"filename": re.compile(r'^.*.(bzl,jy,py,pyi,pyw,sage,sc,tac)$', re.IGNORECASE),"content":None,},
    "py+ul4": {"filename": re.compile(r'^.*.(pyul4)$', re.IGNORECASE),"content":None,},
    "py2tb": {"filename": re.compile(r'^.*.(py2tb)$', re.IGNORECASE),"content":None,},
    "py3": {"filename": re.compile(r'^.*.(bzl,jy,py,pyi,pyw,sage,sc,tac)$', re.IGNORECASE),"content":None,},
    "py3tb": {"filename": re.compile(r'^.*.(py3tb,pytb)$', re.IGNORECASE),"content":None,},
    "pyi": {"filename": re.compile(r'^.*.(bzl,jy,py,pyi,pyw,sage,sc,tac)$', re.IGNORECASE),"content":None,},
    "pypy": {"filename": re.compile(r'^.*.(pypylog)$', re.IGNORECASE),"content":None,},
    "pypylog": {"filename": re.compile(r'^.*.(pypylog)$', re.IGNORECASE),"content":None,},
    "pyrex": {"filename": re.compile(r'^.*.(pxd,pxi,pyx)$', re.IGNORECASE),"content":None,},
    "pytb": {"filename": re.compile(r'^.*.(py3tb,pytb)$', re.IGNORECASE),"content":None,},
    "python": {"filename": re.compile(r'^.*.(bzl,jy,py,pyi,pyw,sage,sc,tac)$', re.IGNORECASE),"content":None,},
    "python3": {"filename": re.compile(r'^.*.(bzl,jy,py,pyi,pyw,sage,sc,tac)$', re.IGNORECASE),"content":None,},
    "pyx": {"filename": re.compile(r'^.*.(pxd,pxi,pyx)$', re.IGNORECASE),"content":None,},
    "q": {"filename": re.compile(r'^.*.(q)$', re.IGNORECASE),"content":None,},
    "qbasic": {"filename": re.compile(r'^.*.(BAS,bas)$', re.IGNORECASE),"content":None,},
    "qbs": {"filename": re.compile(r'^.*.(qbs,qml)$', re.IGNORECASE),"content":None,},
    "ql": {"filename": re.compile(r'^.*.(ql,qll)$', re.IGNORECASE),"content":None,},
    "qlik": {"filename": re.compile(r'^.*.(qvs,qvw)$', re.IGNORECASE),"content":None,},
    "qlikscript": {"filename": re.compile(r'^.*.(qvs,qvw)$', re.IGNORECASE),"content":None,},
    "qliksense": {"filename": re.compile(r'^.*.(qvs,qvw)$', re.IGNORECASE),"content":None,},
    "qlikview": {"filename": re.compile(r'^.*.(qvs,qvw)$', re.IGNORECASE),"content":None,},
    "qml": {"filename": re.compile(r'^.*.(qbs,qml)$', re.IGNORECASE),"content":None,},
    "qvt": {"filename": re.compile(r'^.*.(qvto)$', re.IGNORECASE),"content":None,},
    "qvto": {"filename": re.compile(r'^.*.(qvto)$', re.IGNORECASE),"content":None,},
    "r": {"filename": re.compile(r'^.*.(R,S)$', re.IGNORECASE),"content":None,},
    "racket": {"filename": re.compile(r'^.*.(rkt,rktd,rktl)$', re.IGNORECASE),"content":None,},
    "ragel-c": {"filename": re.compile(r'^.*.(rl)$', re.IGNORECASE),"content":None,},
    "ragel-cpp": {"filename": re.compile(r'^.*.(rl)$', re.IGNORECASE),"content":None,},
    "ragel-d": {"filename": re.compile(r'^.*.(rl)$', re.IGNORECASE),"content":None,},
    "ragel-em": {"filename": re.compile(r'^.*.(rl)$', re.IGNORECASE),"content":None,},
    "ragel-java": {"filename": re.compile(r'^.*.(rl)$', re.IGNORECASE),"content":None,},
    "ragel-objc": {"filename": re.compile(r'^.*.(rl)$', re.IGNORECASE),"content":None,},
    "ragel-rb": {"filename": re.compile(r'^.*.(rl)$', re.IGNORECASE),"content":None,},
    "ragel-ruby": {"filename": re.compile(r'^.*.(rl)$', re.IGNORECASE),"content":None,},
    "raku": {"filename": re.compile(r'^.*.(6pl,6pm,nqp,p6,p6l,p6m,pl,pl6,pm,pm6,raku,rakudoc,rakumod,rakutest,t)$', re.IGNORECASE),"content":None,},
    "rb": {"filename": re.compile(r'^.*.(duby,gemspec,rake,rb,rbw,rbx)$', re.IGNORECASE),"content":None,},
    "rconsole": {"filename": re.compile(r'^.*.(Rout)$', re.IGNORECASE),"content":None,},
    "rd": {"filename": re.compile(r'^.*.(Rd)$', re.IGNORECASE),"content":None,},
    "react": {"filename": re.compile(r'^.*.(jsx,react)$', re.IGNORECASE),"content":None,},
    "reason": {"filename": re.compile(r'^.*.(re,rei)$', re.IGNORECASE),"content":None,},
    "reasonml": {"filename": re.compile(r'^.*.(re,rei)$', re.IGNORECASE),"content":None,},
    "rebol": {"filename": re.compile(r'^.*.(r,r3,reb)$', re.IGNORECASE),"content":None,},
    "red": {"filename": re.compile(r'^.*.(red,reds)$', re.IGNORECASE),"content":None,},
    "red/system": {"filename": re.compile(r'^.*.(red,reds)$', re.IGNORECASE),"content":None,},
    "redcode": {"filename": re.compile(r'^.*.(cw)$', re.IGNORECASE),"content":None,},
    "registry": {"filename": re.compile(r'^.*.(reg)$', re.IGNORECASE),"content":None,},
    "rego": {"filename": re.compile(r'^.*.(rego)$', re.IGNORECASE),"content":None,},
    "rest": {"filename": re.compile(r'^.*.(rest,rst)$', re.IGNORECASE),"content":None,},
    "restructuredtext": {"filename": re.compile(r'^.*.(rest,rst)$', re.IGNORECASE),"content":None,},
    "rexx": {"filename": re.compile(r'^.*.(arexx,rex,rexx,rx)$', re.IGNORECASE),"content":None,},
    "rhtml": {"filename": re.compile(r'^.*.(rhtml)$', re.IGNORECASE),"content":None,},
    "ride": {"filename": re.compile(r'^.*.(ride)$', re.IGNORECASE),"content":None,},
    "rita": {"filename": re.compile(r'^.*.(rita)$', re.IGNORECASE),"content":None,},
    "rkt": {"filename": re.compile(r'^.*.(rkt,rktd,rktl)$', re.IGNORECASE),"content":None,},
    "rnc": {"filename": re.compile(r'^.*.(rnc)$', re.IGNORECASE),"content":None,},
    "rng-compact": {"filename": re.compile(r'^.*.(rnc)$', re.IGNORECASE),"content":None,},
    "roboconf-graph": {"filename": re.compile(r'^.*.(graph)$', re.IGNORECASE),"content":None,},
    "roboconf-instances": {"filename": re.compile(r'^.*.(instances)$', re.IGNORECASE),"content":None,},
    "robotframework": {"filename": re.compile(r'^.*.(resource,robot)$', re.IGNORECASE),"content":None,},
    "rout": {"filename": re.compile(r'^.*.(Rout)$', re.IGNORECASE),"content":None,},
    "rql": {"filename": re.compile(r'^.*.(rql)$', re.IGNORECASE),"content":None,},
    "rs": {"filename": re.compile(r'^.*.(rs,rs.in)$', re.IGNORECASE),"content":None,},
    "rsl": {"filename": re.compile(r'^.*.(rsl)$', re.IGNORECASE),"content":None,},
    "rst": {"filename": re.compile(r'^.*.(rest,rst)$', re.IGNORECASE),"content":None,},
    "rts": {"filename": re.compile(r'^.*.(rts)$', re.IGNORECASE),"content":None,},
    "ruby": {"filename": re.compile(r'^.*.(duby,gemspec,rake,rb,rbw,rbx)$', re.IGNORECASE),"content":None,},
    "rust": {"filename": re.compile(r'^.*.(rs,rs.in)$', re.IGNORECASE),"content":None,},
    "s": {"filename": re.compile(r'^.*.(R,S)$', re.IGNORECASE),"content":None,},
    "sage": {"filename": re.compile(r'^.*.(bzl,jy,py,pyi,pyw,sage,sc,tac)$', re.IGNORECASE),"content":None,},
    "salt": {"filename": re.compile(r'^.*.(sls,yaml.j2,yaml.jinja2,yml.j2,yml.jinja2)$', re.IGNORECASE),"content":None,},
    "sarl": {"filename": re.compile(r'^.*.(sarl)$', re.IGNORECASE),"content":None,},
    "sas": {"filename": re.compile(r'^.*.(SAS,sas)$', re.IGNORECASE),"content":None,},
    "sass": {"filename": re.compile(r'^.*.(sass)$', re.IGNORECASE),"content":None,},
    "savi": {"filename": re.compile(r'^.*.(savi)$', re.IGNORECASE),"content":None,},
    "sbatch": {"filename": re.compile(r'^.*.(sl)$', re.IGNORECASE),"content":None,},
    "sc": {"filename": re.compile(r'^.*.(sc,scd)$', re.IGNORECASE),"content":None,},
    "scala": {"filename": re.compile(r'^.*.(scala)$', re.IGNORECASE),"content":None,},
    "scaml": {"filename": re.compile(r'^.*.(scaml)$', re.IGNORECASE),"content":None,},
    "scd": {"filename": re.compile(r'^.*.(scd,scdoc)$', re.IGNORECASE),"content":None,},
    "scdoc": {"filename": re.compile(r'^.*.(scd,scdoc)$', re.IGNORECASE),"content":None,},
    "scheme": {"filename": re.compile(r'^.*.(scm,ss)$', re.IGNORECASE),"content":None,},
    "scilab": {"filename": re.compile(r'^.*.(sce,sci,tst)$', re.IGNORECASE),"content":None,},
    "scm": {"filename": re.compile(r'^.*.(scm,ss)$', re.IGNORECASE),"content":None,},
    "scss": {"filename": re.compile(r'^.*.(scss)$', re.IGNORECASE),"content":None,},
    "sed": {"filename": re.compile(r'^.*.([gs]sed,sed)$', re.IGNORECASE),"content":None,},
    "sgf": {"filename": re.compile(r'^.*.(sgf)$', re.IGNORECASE),"content":None,},
    "sh": {"filename": re.compile(r'^.*.(bash,ebuild,eclass,exheres-0,exlib,ksh,sh,zsh)$', re.IGNORECASE),"content":None,},
    "shell": {"filename": re.compile(r'^.*.(bash,ebuild,eclass,exheres-0,exlib,ksh,sh,zsh)$', re.IGNORECASE),"content":None,},
    "shell-session": {"filename": re.compile(r'^.*.(sh-session,shell-session)$', re.IGNORECASE),"content":None,},
    "shen": {"filename": re.compile(r'^.*.(shen)$', re.IGNORECASE),"content":None,},
    "shex": {"filename": re.compile(r'^.*.(shex)$', re.IGNORECASE),"content":None,},
    "shexc": {"filename": re.compile(r'^.*.(shex)$', re.IGNORECASE),"content":None,},
    "sieve": {"filename": re.compile(r'^.*.(sieve,siv)$', re.IGNORECASE),"content":None,},
    "silver": {"filename": re.compile(r'^.*.(sil,vpr)$', re.IGNORECASE),"content":None,},
    "singularity": {"filename": re.compile(r'^.*.(def)$', re.IGNORECASE),"content":None,},
    "slash": {"filename": re.compile(r'^.*.(sla)$', re.IGNORECASE),"content":None,},
    "slim": {"filename": re.compile(r'^.*.(slim)$', re.IGNORECASE),"content":None,},
    "sls": {"filename": re.compile(r'^.*.(sls,yaml.j2,yaml.jinja2,yml.j2,yml.jinja2)$', re.IGNORECASE),"content":None,},
    "slurm": {"filename": re.compile(r'^.*.(sl)$', re.IGNORECASE),"content":None,},
    "smali": {"filename": re.compile(r'^.*.(smali)$', re.IGNORECASE),"content":None,},
    "smalltalk": {"filename": re.compile(r'^.*.(st)$', re.IGNORECASE),"content":None,},
    "smarty": {"filename": re.compile(r'^.*.(tpl)$', re.IGNORECASE),"content":None,},
    "smithy": {"filename": re.compile(r'^.*.(smithy)$', re.IGNORECASE),"content":None,},
    "sml": {"filename": re.compile(r'^.*.(fun,sig,sml)$', re.IGNORECASE),"content":None,},
    "snbt": {"filename": re.compile(r'^.*.(snbt)$', re.IGNORECASE),"content":None,},
    "snobol": {"filename": re.compile(r'^.*.(snobol)$', re.IGNORECASE),"content":None,},
    "snowball": {"filename": re.compile(r'^.*.(sbl)$', re.IGNORECASE),"content":None,},
    "sobas": {"filename": re.compile(r'^.*.(bas,vb)$', re.IGNORECASE),"content":None,},
    "solidity": {"filename": re.compile(r'^.*.(sol)$', re.IGNORECASE),"content":None,},
    "sophia": {"filename": re.compile(r'^.*.(aes)$', re.IGNORECASE),"content":None,},
    "sp": {"filename": re.compile(r'^.*.(sp)$', re.IGNORECASE),"content":None,},
    "sparql": {"filename": re.compile(r'^.*.(rq,sparql)$', re.IGNORECASE),"content":None,},
    "spec": {"filename": re.compile(r'^.*.(spec)$', re.IGNORECASE),"content":None,},
    "spice": {"filename": re.compile(r'^.*.(spice)$', re.IGNORECASE),"content":None,},
    "spicelang": {"filename": re.compile(r'^.*.(spice)$', re.IGNORECASE),"content":None,},
    "spitfire": {"filename": re.compile(r'^.*.(spt,tmpl)$', re.IGNORECASE),"content":None,},
    "splus": {"filename": re.compile(r'^.*.(R,S)$', re.IGNORECASE),"content":None,},
    "sql": {"filename": re.compile(r'^.*.(sql)$', re.IGNORECASE),"content":None,},
    "sql+jinja": {"filename": re.compile(r'^.*.(sql,sql.j2,sql.jinja2)$', re.IGNORECASE),"content":None,},
    "sqlite3": {"filename": re.compile(r'^.*.(sqlite3-console)$', re.IGNORECASE),"content":None,},
    "squeak": {"filename": re.compile(r'^.*.(st)$', re.IGNORECASE),"content":None,},
    "ssed": {"filename": re.compile(r'^.*.([gs]sed,sed)$', re.IGNORECASE),"content":None,},
    "ssp": {"filename": re.compile(r'^.*.(ssp)$', re.IGNORECASE),"content":None,},
    "st": {"filename": re.compile(r'^.*.(st)$', re.IGNORECASE),"content":None,},
    "stan": {"filename": re.compile(r'^.*.(stan)$', re.IGNORECASE),"content":None,},
    "starlark": {"filename": re.compile(r'^.*.(bzl,jy,py,pyi,pyw,sage,sc,tac)$', re.IGNORECASE),"content":None,},
    "stata": {"filename": re.compile(r'^.*.(ado,do)$', re.IGNORECASE),"content":None,},
    "supercollider": {"filename": re.compile(r'^.*.(sc,scd)$', re.IGNORECASE),"content":None,},
    "sv": {"filename": re.compile(r'^.*.(sv,svh)$', re.IGNORECASE),"content":None,},
    "swift": {"filename": re.compile(r'^.*.(swift)$', re.IGNORECASE),"content":None,},
    "swig": {"filename": re.compile(r'^.*.(i,swg)$', re.IGNORECASE),"content":None,},
    "systemd": {"filename": re.compile(r'^.*.(automount,device,mount,path,scope,service,slice,socket,swap,target,timer)$', re.IGNORECASE),"content":None,},
    "systemverilog": {"filename": re.compile(r'^.*.(sv,svh)$', re.IGNORECASE),"content":None,},
    "t-sql": {"filename": re.compile(r'^.*.(sql)$', re.IGNORECASE),"content":None,},
    "tablegen": {"filename": re.compile(r'^.*.(td)$', re.IGNORECASE),"content":None,},
    "tact": {"filename": re.compile(r'^.*.(tact)$', re.IGNORECASE),"content":None,},
    "tads3": {"filename": re.compile(r'^.*.(t)$', re.IGNORECASE),"content":None,},
    "tal": {"filename": re.compile(r'^.*.(tal)$', re.IGNORECASE),"content":None,},
    "tap": {"filename": re.compile(r'^.*.(tap)$', re.IGNORECASE),"content":None,},
    "tasm": {"filename": re.compile(r'^.*.(ASM,asm,tasm)$', re.IGNORECASE),"content":None,},
    "tcl": {"filename": re.compile(r'^.*.(rvt,tcl)$', re.IGNORECASE),"content":None,},
    "tcsh": {"filename": re.compile(r'^.*.(csh,tcsh)$', re.IGNORECASE),"content":None,},
    "td": {"filename": re.compile(r'^.*.(td)$', re.IGNORECASE),"content":None,},
    "tea": {"filename": re.compile(r'^.*.(tea)$', re.IGNORECASE),"content":None,},
    "teal": {"filename": re.compile(r'^.*.(teal)$', re.IGNORECASE),"content":None,},
    "teraterm": {"filename": re.compile(r'^.*.(ttl)$', re.IGNORECASE),"content":None,},
    "teratermmacro": {"filename": re.compile(r'^.*.(ttl)$', re.IGNORECASE),"content":None,},
    "terraform": {"filename": re.compile(r'^.*.(hcl,tf)$', re.IGNORECASE),"content":None,},
    "tex": {"filename": re.compile(r'^.*.(aux,tex,toc)$', re.IGNORECASE),"content":None,},
    "text": {"filename": re.compile(r'^.*.(txt)$', re.IGNORECASE),"content":None,},
    "tf": {"filename": re.compile(r'^.*.(hcl,tf)$', re.IGNORECASE),"content":None,},
    "thingsdb": {"filename": re.compile(r'^.*.(ti)$', re.IGNORECASE),"content":None,},
    "thrift": {"filename": re.compile(r'^.*.(thrift)$', re.IGNORECASE),"content":None,},
    "ti": {"filename": re.compile(r'^.*.(ti)$', re.IGNORECASE),"content":None,},
    "tid": {"filename": re.compile(r'^.*.(tid)$', re.IGNORECASE),"content":None,},
    "tlb": {"filename": re.compile(r'^.*.(tlb)$', re.IGNORECASE),"content":None,},
    "tnt": {"filename": re.compile(r'^.*.(tnt)$', re.IGNORECASE),"content":None,},
    "todotxt": {"filename": re.compile(r'^.*.(todotxt)$', re.IGNORECASE),"content":None,},
    "toml": {"filename": re.compile(r'^.*.(toml)$', re.IGNORECASE),"content":None,},
    "trafficscript": {"filename": re.compile(r'^.*.(rts)$', re.IGNORECASE),"content":None,},
    "treetop": {"filename": re.compile(r'^.*.(treetop,tt)$', re.IGNORECASE),"content":None,},
    "ts": {"filename": re.compile(r'^.*.(ts)$', re.IGNORECASE),"content":None,},
    "tsql": {"filename": re.compile(r'^.*.(sql)$', re.IGNORECASE),"content":None,},
    "tsx": {"filename": re.compile(r'^.*.(tsx)$', re.IGNORECASE),"content":None,},
    "ttl": {"filename": re.compile(r'^.*.(ttl)$', re.IGNORECASE),"content":None,},
    "turtle": {"filename": re.compile(r'^.*.(ttl)$', re.IGNORECASE),"content":None,},
    "typescript": {"filename": re.compile(r'^.*.(ts)$', re.IGNORECASE),"content":None,},
    "typoscript": {"filename": re.compile(r'^.*.(typoscript)$', re.IGNORECASE),"content":None,},
    "typst": {"filename": re.compile(r'^.*.(typ)$', re.IGNORECASE),"content":None,},
    "ucode": {"filename": re.compile(r'^.*.(u,u1,u2)$', re.IGNORECASE),"content":None,},
    "udiff": {"filename": re.compile(r'^.*.(diff,patch)$', re.IGNORECASE),"content":None,},
    "ul4": {"filename": re.compile(r'^.*.(ul4)$', re.IGNORECASE),"content":None,},
    "unicon": {"filename": re.compile(r'^.*.(icn)$', re.IGNORECASE),"content":None,},
    "urbiscript": {"filename": re.compile(r'^.*.(u)$', re.IGNORECASE),"content":None,},
    "usd": {"filename": re.compile(r'^.*.(usd,usda)$', re.IGNORECASE),"content":None,},
    "usda": {"filename": re.compile(r'^.*.(usd,usda)$', re.IGNORECASE),"content":None,},
    "uxntal": {"filename": re.compile(r'^.*.(tal)$', re.IGNORECASE),"content":None,},
    "v": {"filename": re.compile(r'^.*.(v)$', re.IGNORECASE),"content":None,},
    "vala": {"filename": re.compile(r'^.*.(vala,vapi)$', re.IGNORECASE),"content":None,},
    "vapi": {"filename": re.compile(r'^.*.(vala,vapi)$', re.IGNORECASE),"content":None,},
    "vb.net": {"filename": re.compile(r'^.*.(bas,vb)$', re.IGNORECASE),"content":None,},
    "vbnet": {"filename": re.compile(r'^.*.(bas,vb)$', re.IGNORECASE),"content":None,},
    "vbscript": {"filename": re.compile(r'^.*.(VBS,vbs)$', re.IGNORECASE),"content":None,},
    "vcl": {"filename": re.compile(r'^.*.(vcl)$', re.IGNORECASE),"content":None,},
    "velocity": {"filename": re.compile(r'^.*.(fhtml,vm)$', re.IGNORECASE),"content":None,},
    "verifpal": {"filename": re.compile(r'^.*.(vp)$', re.IGNORECASE),"content":None,},
    "verilog": {"filename": re.compile(r'^.*.(v)$', re.IGNORECASE),"content":None,},
    "vfp": {"filename": re.compile(r'^.*.(PRG,prg)$', re.IGNORECASE),"content":None,},
    "vgl": {"filename": re.compile(r'^.*.(rpf)$', re.IGNORECASE),"content":None,},
    "vhdl": {"filename": re.compile(r'^.*.(vhd,vhdl)$', re.IGNORECASE),"content":None,},
    "vim": {"filename": re.compile(r'^.*.(vim)$', re.IGNORECASE),"content":None,},
    "visual-basic": {"filename": re.compile(r'^.*.(bas,vb)$', re.IGNORECASE),"content":None,},
    "visualbasic": {"filename": re.compile(r'^.*.(bas,vb)$', re.IGNORECASE),"content":None,},
    "visualprolog": {"filename": re.compile(r'^.*.(cl,i,pack,ph,pro)$', re.IGNORECASE),"content":None,},
    "visualprologgrammar": {"filename": re.compile(r'^.*.(vipgrm)$', re.IGNORECASE),"content":None,},
    "vue": {"filename": re.compile(r'^.*.(vue)$', re.IGNORECASE),"content":None,},
    "vyper": {"filename": re.compile(r'^.*.(vy)$', re.IGNORECASE),"content":None,},
    "wast": {"filename": re.compile(r'^.*.(wast,wat)$', re.IGNORECASE),"content":None,},
    "wat": {"filename": re.compile(r'^.*.(wast,wat)$', re.IGNORECASE),"content":None,},
    "wdiff": {"filename": re.compile(r'^.*.(wdiff)$', re.IGNORECASE),"content":None,},
    "webidl": {"filename": re.compile(r'^.*.(webidl)$', re.IGNORECASE),"content":None,},
    "wgsl": {"filename": re.compile(r'^.*.(wgsl)$', re.IGNORECASE),"content":None,},
    "whiley": {"filename": re.compile(r'^.*.(whiley)$', re.IGNORECASE),"content":None,},
    "winbatch": {"filename": re.compile(r'^.*.(bat,cmd)$', re.IGNORECASE),"content":None,},
    "winbugs": {"filename": re.compile(r'^.*.(bug)$', re.IGNORECASE),"content":None,},
    "wowtoc": {"filename": re.compile(r'^.*.(toc)$', re.IGNORECASE),"content":None,},
    "wren": {"filename": re.compile(r'^.*.(wren)$', re.IGNORECASE),"content":None,},
    "x++": {"filename": re.compile(r'^.*.(xpp)$', re.IGNORECASE),"content":None,},
    "x10": {"filename": re.compile(r'^.*.(x10)$', re.IGNORECASE),"content":None,},
    "xbase": {"filename": re.compile(r'^.*.(PRG,prg)$', re.IGNORECASE),"content":None,},
    "xml": {"filename": re.compile(r'^.*.(rss,wsdl,wsf,xml,xsd,xsl,xslt)$', re.IGNORECASE),"content":None,},
    "xml+django": {"filename": re.compile(r'^.*.(xml.j2,xml.jinja2)$', re.IGNORECASE),"content":None,},
    "xml+genshi": {"filename": re.compile(r'^.*.(kid)$', re.IGNORECASE),"content":None,},
    "xml+jinja": {"filename": re.compile(r'^.*.(xml.j2,xml.jinja2)$', re.IGNORECASE),"content":None,},
    "xml+kid": {"filename": re.compile(r'^.*.(kid)$', re.IGNORECASE),"content":None,},
    "xml+ul4": {"filename": re.compile(r'^.*.(xmlul4)$', re.IGNORECASE),"content":None,},
    "xpp": {"filename": re.compile(r'^.*.(xpp)$', re.IGNORECASE),"content":None,},
    "xq": {"filename": re.compile(r'^.*.(xq,xql,xqm,xquery,xqy)$', re.IGNORECASE),"content":None,},
    "xql": {"filename": re.compile(r'^.*.(xq,xql,xqm,xquery,xqy)$', re.IGNORECASE),"content":None,},
    "xqm": {"filename": re.compile(r'^.*.(xq,xql,xqm,xquery,xqy)$', re.IGNORECASE),"content":None,},
    "xquery": {"filename": re.compile(r'^.*.(xq,xql,xqm,xquery,xqy)$', re.IGNORECASE),"content":None,},
    "xqy": {"filename": re.compile(r'^.*.(xq,xql,xqm,xquery,xqy)$', re.IGNORECASE),"content":None,},
    "xslt": {"filename": re.compile(r'^.*.(xpl,xsl,xslt)$', re.IGNORECASE),"content":None,},
    "xten": {"filename": re.compile(r'^.*.(x10)$', re.IGNORECASE),"content":None,},
    "xtend": {"filename": re.compile(r'^.*.(xtend)$', re.IGNORECASE),"content":None,},
    "xul+mozpreproc": {"filename": re.compile(r'^.*.(xul.in)$', re.IGNORECASE),"content":None,},
    "yaml": {"filename": re.compile(r'^.*.(yaml,yml)$', re.IGNORECASE),"content":None,},
    "yaml+jinja": {"filename": re.compile(r'^.*.(sls,yaml.j2,yaml.jinja2,yml.j2,yml.jinja2)$', re.IGNORECASE),"content":None,},
    "yang": {"filename": re.compile(r'^.*.(yang)$', re.IGNORECASE),"content":None,},
    "yar": {"filename": re.compile(r'^.*.(yar)$', re.IGNORECASE),"content":None,},
    "yara": {"filename": re.compile(r'^.*.(yar)$', re.IGNORECASE),"content":None,},
    "zeek": {"filename": re.compile(r'^.*.(bro,zeek)$', re.IGNORECASE),"content":None,},
    "zephir": {"filename": re.compile(r'^.*.(zep)$', re.IGNORECASE),"content":None,},
    "zetasql": {"filename": re.compile(r'^.*.(googlesql,googlesql.sql)$', re.IGNORECASE),"content":None,},
    "zig": {"filename": re.compile(r'^.*.(zig)$', re.IGNORECASE),"content":None,},
    "zone": {"filename": re.compile(r'^.*.(zone)$', re.IGNORECASE),"content":None,},
    "zsh": {"filename": re.compile(r'^.*.(bash,ebuild,eclass,exheres-0,exlib,ksh,sh,zsh)$', re.IGNORECASE),"content":None,},
    "🔥": {"filename": re.compile(r'^.*.(mojo,🔥)$', re.IGNORECASE),"content":None,},
}